// MEANING IDENTITY — the one place the app answers "are these the same meaning?"
//
// THE CONTRACT (this file is the seam between the data track and the content
// model; keeping ALL synonymy logic on one side is what stops the two from
// drifting):
//
//   • The DATA track owns every judgment. Its ingest pipeline emits
//     `src/data/generated/meaning-registry.json` — a plain `Record<gloss,
//     MeaningId>` mapping EVERY gloss string the app carries (kanji meanings,
//     word-definition glosses, radical meanings) to a canonical MeaningId. That
//     mapping folds together BOTH tiers:
//        - surface variants  — "one" / "1" / "one (1)" / "to speak" / "speak"
//        - true synonyms      — "man" / "person", "speak" / "talk", "jar" / "tin can"
//     Generated by normalize → embed-shortlist → LLM-judge → HUMAN REVIEW, then
//     baked. See docs/architecture-refactor.md §"Meaning model".
//
//   • The CONTENT model only READS, via `canonicalMeaningId`. It must NEVER
//     normalize or compare gloss strings itself — every consumer that wants to
//     know if two glosses mean the same thing calls this function. That is the
//     single-source rule; a second normalization/synonymy implementation over
//     here is exactly the divergence we are avoiding.
//
// TWO HARD CONSTRAINTS on the data track's ids:
//
//   1. STABLE across regenerations. A MeaningId is an identity, like a
//      `definitionId` or a fact id — if a corpus/model update silently renamed
//      it, everything keyed on it (cost grouping, "taught this meaning" records)
//      would shift. Pick stable slugs; never let the id ride on the English
//      wording it happened to get.
//
//   2. NON-DESTRUCTIVE to fact history. MeaningId does NOT re-key facts. Facts
//      stay keyed as they are (entry/aspect), and history stays on those fact
//      ids — the same care CEJC took with `legacyUnqualifiedReading`. MeaningId
//      is a DERIVED grouping used to dedupe cost and to pick one representative
//      fact to drill per meaning; it never rewrites what a learner has answered.

import REGISTRY from "@/data/generated/meaning-registry.json";

const ENTRY_BRAND: unique symbol = Symbol("MeaningId");

/** A canonical meaning identity. Two glosses share one iff the data track judged
 * them the same meaning. Opaque — never parse or compare it as text. */
export type MeaningId = string & { readonly [ENTRY_BRAND]: true };

const MAP = REGISTRY as Record<string, string>;

/**
 * The canonical MeaningId for a gloss. A pure lookup into the reviewed registry;
 * NO normalization or synonymy logic lives here. Until a gloss is in the registry
 * it is its own meaning (returns the gloss verbatim) — so the app degrades to
 * exact-match dedup, never to a wrong merge, while the registry is still being
 * built. That fallback is why shipping a stub `{}` registry is safe.
 */
export function canonicalMeaningId(gloss: string): MeaningId {
  return (MAP[gloss] ?? gloss) as MeaningId;
}

/** Whether the registry has an opinion about this gloss yet (vs the identity
 * fallback). Useful for coverage reporting while the registry is populated. */
export function isRegisteredMeaning(gloss: string): boolean {
  return gloss in MAP;
}
