// Run: node --import ./src/lib/conjugate/test-hooks.mjs --test \
//        src/lib/strokes.test.ts
//
// The stroke-order assets (src/data/generated/strokes/{hiragana,katakana}.json,
// generated by scripts/ingest/kanjivg.mjs from KanjiVG) are what the "how it's
// written" section draws. These pin the contract the renderer relies on:
//
//   - they parse, and every base hiragana AND katakana is present — a glyph
//     dropped by a future ingest run fails here rather than silently rendering
//     the fallback;
//   - the vowels of each script have real, ordered stroke data, one number label
//     per stroke (numbers[i] labels strokes[i]);
//   - a glyph with no data — a kanji — is simply absent, which the loader turns
//     into null and the section renders as the whole-shape fallback rather than
//     crashing.
//
// The lookup is read straight off the JSON here (the hook that wraps it is React
// and untestable in this harness, exactly like lesson-prefs); the behaviour that
// matters lives in the data shape, and that is what this checks.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, test } from "node:test";

import { scriptOf } from "./strokes.ts";

interface GlyphStrokes {
  strokes: string[];
  numbers: [number, number][];
}

type StrokeMap = Record<string, GlyphStrokes | undefined>;

function read(name: string): StrokeMap {
  const asset = fileURLToPath(
    new URL(`../data/generated/strokes/${name}.json`, import.meta.url),
  );
  return JSON.parse(readFileSync(asset, "utf-8")) as StrokeMap;
}

/** Every ingested script, merged the way the loader's per-script lookup adds up
 * from the caller's side: one glyph in, its strokes or null out. */
const DATA: StrokeMap = { ...read("hiragana"), ...read("katakana") };

/** How the loader answers a lookup: the entry, or null when a glyph has no
 * data (see useGlyphStrokes in strokes.ts). */
function lookup(glyph: string): GlyphStrokes | null {
  return DATA[glyph] ?? null;
}

/** The 46 base glyphs of each script, in gojūon order — the sets the ingest
 * emits, so anything missing from either is a broken run. */
const SCRIPTS = [
  {
    name: "hiragana",
    vowels: [..."あいうえお"],
    base: [
      ..."あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん",
    ],
  },
  {
    name: "katakana",
    vowels: [..."アイウエオ"],
    base: [
      ..."アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン",
    ],
  },
];

describe("stroke-order asset", () => {
  for (const { name, vowels, base } of SCRIPTS) {
    test(`all 46 base ${name} are present`, () => {
      assert.equal(base.length, 46);
      const missing = base.filter((g) => !lookup(g));
      assert.deepEqual(missing, [], `${name} missing from ingest: ${missing.join(" ")}`);
    });

    test(`${name} vowels load with ordered strokes and aligned number labels`, () => {
      for (const v of vowels) {
        const entry = lookup(v);
        assert.ok(entry, `missing ${v}`);
        // Real strokes: at least one, every one a non-empty SVG path starting M.
        assert.ok(entry.strokes.length >= 1, `${v} has no strokes`);
        for (const d of entry.strokes) {
          assert.equal(typeof d, "string");
          assert.match(d, /^M/, `${v} stroke isn't a path: ${d.slice(0, 12)}`);
        }
        // One number label per stroke, each an [x, y] pair on the 109 grid.
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${v}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
        for (const [x, y] of entry.numbers) {
          assert.ok(x >= 0 && x <= 109 && y >= 0 && y <= 109, `${v} label off-grid`);
        }
      }
    });

    test(`every ${name} entry has one label per stroke`, () => {
      for (const g of base) {
        const entry = lookup(g)!;
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${g}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
      }
    });
  }

  test("known stroke counts are right", () => {
    // Hand-counted against the glyphs themselves; a wrong count means the
    // ingest picked up the wrong character or dropped a path.
    const counts: Record<string, number> = {
      あ: 3, し: 1,
      ア: 2, イ: 2, ン: 2, ヲ: 3, ノ: 1, フ: 1, ホ: 4, ネ: 4,
    };
    for (const [g, n] of Object.entries(counts)) {
      assert.equal(lookup(g)!.strokes.length, n, `${g} should be ${n} strokes`);
    }
  });

  test("a glyph with no data degrades to null, not a throw", () => {
    // Kanji isn't ingested — the loader returns null and the section falls back
    // to the whole-shape view.
    assert.equal(lookup("水"), null); // kanji
    assert.equal(lookup(""), null); // the collapsed sentinel
  });
});

describe("scriptOf: which asset to fetch, if any", () => {
  test("a single kana picks its own script's asset", () => {
    assert.equal(scriptOf("あ"), "hiragana");
    assert.equal(scriptOf("ん"), "hiragana");
    assert.equal(scriptOf("ア"), "katakana");
    assert.equal(scriptOf("ヲ"), "katakana");
  });

  test("nothing is fetched for a glyph with no ingested asset", () => {
    assert.equal(scriptOf("水"), null); // kanji
    assert.equal(scriptOf(""), null); // the collapsed-section sentinel
    assert.equal(scriptOf("〜"), null); // punctuation
    assert.equal(scriptOf("A"), null);
  });

  // THE BUG THIS PINS: これ starts with hiragana, so a first-codepoint-only
  // test said "hiragana" and the whole hiragana map was fetched over the
  // network — and then missed, because the map is keyed by ONE character.
  // A download that could not possibly succeed. Multi-character strings must
  // settle to null WITHOUT asking for an asset.
  test("a multi-character string never asks for an asset", () => {
    for (const s of ["これ", "がっこう", "学生", "〜てから", "サッカー"]) {
      assert.equal(scriptOf(s), null, `${s} must not trigger a stroke fetch`);
      // And the reason it must not: the asset could never have answered it.
      assert.equal(lookup(s), null, `${s} is not a key in the stroke map`);
    }
  });

  test("a glyph outside the BMP still counts as one character", () => {
    // Counted in codepoints, not UTF-16 units: a surrogate pair is one glyph,
    // and must not be rejected as if it were two characters.
    const surrogatePair = "\u{20BB7}"; // 𠮷, a kanji — null for lack of data,
    assert.equal(surrogatePair.length, 2); // not for being "two characters".
    assert.equal([...surrogatePair].length, 1);
    assert.equal(scriptOf(surrogatePair), null);
  });
});
