// Run: node --import ./src/lib/conjugate/test-hooks.mjs --test \
//        src/lib/strokes.test.ts
//
// The stroke-order assets (src/data/generated/strokes/: hiragana.json,
// katakana.json and the 48 kanji-NN.json chunks, generated by
// scripts/ingest/kanjivg.mjs from KanjiVG) are what the "how it's written"
// section draws. These pin the contract the renderer relies on:
//
//   - they parse, and every base hiragana, every base katakana AND every jōyō
//     kanji is present — a glyph dropped by a future ingest run fails here
//     rather than silently rendering the fallback;
//   - the vowels of each script have real, ordered stroke data, one number label
//     per stroke (numbers[i] labels strokes[i]);
//   - a glyph with no data — a non-jōyō kanji — is simply absent, which the
//     loader turns into null and the section renders as the whole-shape fallback
//     rather than crashing;
//   - the kanji chunks stay SMALL and EVENLY sized. That is the whole point of
//     chunking: one chunk is what a reader downloads to see one character drawn,
//     so a chunk quietly growing past a bound is a regression in the thing the
//     split exists to protect.
//
// The lookup is read straight off the JSON here (the hook that wraps it is React
// and untestable in this harness, exactly like lesson-prefs); the behaviour that
// matters lives in the data shape, and that is what this checks.

import assert from "node:assert/strict";
import { readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, test } from "node:test";

import { KANJI_CHUNKS, JOUYOU } from "../data/generated/strokes/kanji-index.ts";
import { KANJI } from "../data/kanji.ts";
import { scriptOf } from "./strokes.ts";

interface GlyphStrokes {
  strokes: string[];
  numbers: [number, number][];
}

type StrokeMap = Record<string, GlyphStrokes | undefined>;

function read(name: string): StrokeMap {
  const asset = fileURLToPath(
    new URL(`../data/generated/strokes/${name}.json`, import.meta.url),
  );
  return JSON.parse(readFileSync(asset, "utf-8")) as StrokeMap;
}

/** The 48 kanji chunks, by id, read once. */
const CHUNKS: StrokeMap[] = Array.from({ length: KANJI_CHUNKS }, (_, n) =>
  read(chunkName(n)),
);

/** `kanji-07` — the basename the ingest writes and the loader asks for. */
function chunkName(n: number): string {
  return `kanji-${String(n).padStart(2, "0")}`;
}

/** Every ingested asset, merged the way the loader's per-asset lookup adds up
 * from the caller's side: one glyph in, its strokes or null out. */
const DATA: StrokeMap = Object.assign(
  {},
  read("hiragana"),
  read("katakana"),
  ...CHUNKS,
);

/** How the loader answers a lookup: the entry, or null when a glyph has no
 * data (see useGlyphStrokes in strokes.ts). */
function lookup(glyph: string): GlyphStrokes | null {
  return DATA[glyph] ?? null;
}

/** The 46 base glyphs of each script, in gojūon order — the sets the ingest
 * emits, so anything missing from either is a broken run. */
const SCRIPTS = [
  {
    name: "hiragana",
    vowels: [..."あいうえお"],
    base: [
      ..."あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん",
    ],
  },
  {
    name: "katakana",
    vowels: [..."アイウエオ"],
    base: [
      ..."アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン",
    ],
  },
];

describe("stroke-order asset", () => {
  for (const { name, vowels, base } of SCRIPTS) {
    test(`all 46 base ${name} are present`, () => {
      assert.equal(base.length, 46);
      const missing = base.filter((g) => !lookup(g));
      assert.deepEqual(missing, [], `${name} missing from ingest: ${missing.join(" ")}`);
    });

    test(`${name} vowels load with ordered strokes and aligned number labels`, () => {
      for (const v of vowels) {
        const entry = lookup(v);
        assert.ok(entry, `missing ${v}`);
        // Real strokes: at least one, every one a non-empty SVG path starting M.
        assert.ok(entry.strokes.length >= 1, `${v} has no strokes`);
        for (const d of entry.strokes) {
          assert.equal(typeof d, "string");
          assert.match(d, /^M/, `${v} stroke isn't a path: ${d.slice(0, 12)}`);
        }
        // One number label per stroke, each an [x, y] pair on the 109 grid.
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${v}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
        for (const [x, y] of entry.numbers) {
          assert.ok(x >= 0 && x <= 109 && y >= 0 && y <= 109, `${v} label off-grid`);
        }
      }
    });

    test(`every ${name} entry has one label per stroke`, () => {
      for (const g of base) {
        const entry = lookup(g)!;
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${g}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
      }
    });
  }

  test("known stroke counts are right", () => {
    // Hand-counted against the glyphs themselves; a wrong count means the
    // ingest picked up the wrong character or dropped a path.
    const counts: Record<string, number> = {
      あ: 3, し: 1,
      ア: 2, イ: 2, ン: 2, ヲ: 3, ノ: 1, フ: 1, ホ: 4, ネ: 4,
    };
    for (const [g, n] of Object.entries(counts)) {
      assert.equal(lookup(g)!.strokes.length, n, `${g} should be ${n} strokes`);
    }
  });

  test("a glyph with no data degrades to null, not a throw", () => {
    // A kanji nobody teaches isn't ingested — the loader returns null and the
    // section falls back to the whole-shape view.
    assert.equal(lookup("龘"), null); // a non-jōyō kanji
    assert.equal(lookup(""), null); // the collapsed sentinel
  });
});

describe("kanji chunks", () => {
  test("every jōyō kanji is in the chunk its codepoint names", () => {
    // Not just "present somewhere": present in the ONE file the loader will
    // fetch for it. A glyph in the wrong chunk is invisible at runtime.
    const missing: string[] = [];
    for (const { c } of KANJI) {
      const entry = CHUNKS[c.codePointAt(0)! % KANJI_CHUNKS][c];
      if (!entry) missing.push(c);
    }
    assert.deepEqual(missing, [], `not in their chunk: ${missing.join(" ")}`);
    assert.equal(KANJI.length, 2136);
  });

  test("every kanji entry has real ordered strokes, one label each", () => {
    for (const { c } of KANJI) {
      const entry = lookup(c)!;
      assert.ok(entry.strokes.length >= 1, `${c} has no strokes`);
      // `M` or `m`: KanjiVG mostly emits an absolute moveto, but a handful
      // (偏 慣 掛 貫 頃) start relative. Both are valid SVG and the renderer
      // hands the `d` straight to the browser, so the test accepts either
      // rather than the absolute-only form the kana happen to use.
      assert.match(entry.strokes[0], /^[Mm]/, `${c} stroke isn't a path`);
      assert.equal(
        entry.numbers.length,
        entry.strokes.length,
        `${c}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
      );
    }
  });

  test("KANJIDIC2's stroke count agrees with KanjiVG's, bar 9 known cases", () => {
    // Two INDEPENDENT sources for the same fact, which is what makes this a
    // real check: a chunk keyed to the wrong character would disagree on the
    // count for hundreds of glyphs, so this is the test that catches a
    // mis-keyed ingest.
    //
    // Nine genuinely disagree, and they are upstream editorial differences, not
    // ingest errors — each SVG's own kvg:element names the character we asked
    // for. Eight are 2010 jōyō additions that KanjiVG draws with the PRINTED
    // component form, one stroke more than KANJIDIC2 counts for the handwritten
    // one (謎 賭 遜 遡 with the two-dot shinnyō, 餅 餌 with 𩙿 for 飠, plus 僅
    // 葛). 牙 goes the other way: KanjiVG draws 4, KANJIDIC2's primary count is
    // 5. Pinned by name so a TENTH disagreement fails this test rather than
    // quietly joining the list.
    const disagree = KANJI.filter(({ c, strokes }) => lookup(c)!.strokes.length !== strokes)
      .map(({ c }) => c)
      .sort();
    assert.deepEqual(disagree, [..."僅牙葛謎賭遜遡餅餌"].sort());
  });

  test("JOUYOU lists exactly the kanji the app teaches", () => {
    // The membership string gates every kanji fetch, so a drift between it and
    // the app's kanji set is either a wasted download or a missing diagram.
    assert.deepEqual([...JOUYOU].sort(), KANJI.map((k) => k.c).sort());
  });

  test("no chunk is big enough to hurt: 48 files, none over 96KB", () => {
    // The bound the split exists to hold. 2.2MB over 48 files is ~46KB each and
    // the largest is ~58KB; 96KB is headroom for a re-ingest, not a target. If
    // this trips, the chunk COUNT needs raising, not the bound.
    const sizes = CHUNKS.map((_, n) =>
      statSync(
        fileURLToPath(
          new URL(`../data/generated/strokes/${chunkName(n)}.json`, import.meta.url),
        ),
      ).size,
    );
    assert.equal(sizes.length, 48);
    const biggest = Math.max(...sizes);
    assert.ok(biggest <= 96 * 1024, `largest chunk is ${(biggest / 1024).toFixed(1)}KB`);
    // And evenly enough spread that no chunk is an outlier: the modulo is only
    // worth using over a range split because it distributes.
    assert.ok(
      biggest <= 2 * Math.min(...sizes),
      `chunks are lopsided: ${(Math.min(...sizes) / 1024).toFixed(1)}KB to ${(biggest / 1024).toFixed(1)}KB`,
    );
  });
});

describe("scriptOf: which asset to fetch, if any", () => {
  test("a single kana picks its own script's asset", () => {
    assert.equal(scriptOf("あ"), "hiragana");
    assert.equal(scriptOf("ん"), "hiragana");
    assert.equal(scriptOf("ア"), "katakana");
    assert.equal(scriptOf("ヲ"), "katakana");
  });

  test("a single jōyō kanji picks the one chunk it lives in", () => {
    for (const c of ["水", "生", "明", "一", "𠮟"]) {
      assert.equal(scriptOf(c), `kanji-${c.codePointAt(0)! % KANJI_CHUNKS}`);
    }
    // And it resolves for ALL of them, not just the handful spelled out.
    const unresolved = KANJI.filter(({ c }) => scriptOf(c) === null);
    assert.deepEqual(unresolved.map((k) => k.c), []);
  });

  test("nothing is fetched for a glyph with no ingested asset", () => {
    // A kanji outside the jōyō set is in no chunk, so naming one for it would
    // buy a download that must miss. It settles to null instead.
    assert.equal(scriptOf("龘"), null);
    assert.equal(scriptOf("怱"), null);
    assert.equal(scriptOf(""), null); // the collapsed-section sentinel
    assert.equal(scriptOf("〜"), null); // punctuation
    assert.equal(scriptOf("A"), null);
  });

  // THE BUG THIS PINS: これ starts with hiragana, so a first-codepoint-only
  // test said "hiragana" and the whole hiragana map was fetched over the
  // network — and then missed, because the map is keyed by ONE character.
  // A download that could not possibly succeed. Multi-character strings must
  // settle to null WITHOUT asking for an asset.
  test("a multi-character string never asks for an asset", () => {
    for (const s of ["これ", "がっこう", "学生", "〜てから", "サッカー"]) {
      assert.equal(scriptOf(s), null, `${s} must not trigger a stroke fetch`);
      // And the reason it must not: the asset could never have answered it.
      assert.equal(lookup(s), null, `${s} is not a key in the stroke map`);
    }
  });

  test("a glyph outside the BMP still counts as one character", () => {
    // Counted in codepoints, not UTF-16 units: a surrogate pair is one glyph,
    // and must not be rejected as if it were two characters.
    const surrogatePair = "\u{20BB7}"; // 𠮷, a kanji — null for lack of data,
    assert.equal(surrogatePair.length, 2); // not for being "two characters".
    assert.equal([...surrogatePair].length, 1);
    assert.equal(scriptOf(surrogatePair), null);
  });
});
