// Run: node --import ./src/lib/conjugate/test-hooks.mjs --test \
//        src/lib/strokes.test.ts
//
// The stroke-order assets (src/data/generated/strokes/: hiragana.json,
// katakana.json and the 48 kanji-NN.json chunks, generated by
// scripts/ingest/kanjivg.mjs from KanjiVG) are what the "how it's written"
// section draws. These pin the contract the renderer relies on:
//
//   - they parse, and every base hiragana, every base katakana AND every jōyō
//     kanji is present — a glyph dropped by a future ingest run fails here
//     rather than silently rendering the fallback;
//   - the vowels of each script have real, ordered stroke data, one number label
//     per stroke (numbers[i] labels strokes[i]);
//   - a glyph with no data — a non-jōyō kanji — is simply absent, which the
//     loader turns into null and the section renders as the whole-shape fallback
//     rather than crashing;
//   - the kanji chunks stay SMALL and EVENLY sized. That is the whole point of
//     chunking: one chunk is what a reader downloads to see one character drawn,
//     so a chunk quietly growing past a bound is a regression in the thing the
//     split exists to protect.
//
// The lookup is read straight off the JSON here (the hook that wraps it is React
// and untestable in this harness, exactly like lesson-prefs); the behaviour that
// matters lives in the data shape, and that is what this checks.

import assert from "node:assert/strict";
import { readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, test } from "node:test";

import {
  KANJI_CHUNKS,
  JOUYOU,
  RADICAL_GLYPHS,
} from "../data/generated/strokes/kanji-index.ts";
import { KANJI } from "../data/kanji.ts";
import { DAKUTEN_ROWS } from "../data/dakuten-rows.ts";
import { SMALL_TO_FULL_HIRAGANA } from "../lib/library/kana-family.ts";
import { pathBBox } from "./svg-path.ts";
import { composeGlyphStrokes, scriptOf, STROKE_GRID } from "./strokes.ts";

/** The union of several bounding boxes — used below to measure a whole
 * multi-stroke glyph rather than one stroke at a time. */
function union(boxes: { xmin: number; xmax: number; ymin: number; ymax: number }[]) {
  return boxes.reduce(
    (acc, b) => ({
      xmin: Math.min(acc.xmin, b.xmin),
      xmax: Math.max(acc.xmax, b.xmax),
      ymin: Math.min(acc.ymin, b.ymin),
      ymax: Math.max(acc.ymax, b.ymax),
    }),
    { xmin: Infinity, xmax: -Infinity, ymin: Infinity, ymax: -Infinity },
  );
}

interface GlyphStrokes {
  strokes: string[];
  numbers: [number, number][];
}

type StrokeMap = Record<string, GlyphStrokes | undefined>;

function read(name: string): StrokeMap {
  const asset = fileURLToPath(
    new URL(`../data/generated/strokes/${name}.json`, import.meta.url),
  );
  return JSON.parse(readFileSync(asset, "utf-8")) as StrokeMap;
}

/** The 48 kanji chunks, by id, read once. */
const CHUNKS: StrokeMap[] = Array.from({ length: KANJI_CHUNKS }, (_, n) =>
  read(chunkName(n)),
);

/** `kanji-07` — the basename the ingest writes and the loader asks for. */
function chunkName(n: number): string {
  return `kanji-${String(n).padStart(2, "0")}`;
}

/** Every ingested asset, merged the way the loader's per-asset lookup adds up
 * from the caller's side: one glyph in, its strokes or null out. */
const DATA: StrokeMap = Object.assign(
  {},
  read("hiragana"),
  read("katakana"),
  ...CHUNKS,
);

/** How the loader answers a lookup: the entry, or null when a glyph has no
 * data (see useGlyphStrokes in strokes.ts). */
function lookup(glyph: string): GlyphStrokes | null {
  return DATA[glyph] ?? null;
}

/** The 46 base glyphs of each script, in gojūon order — the sets the ingest
 * emits, so anything missing from either is a broken run. */
const SCRIPTS = [
  {
    name: "hiragana",
    vowels: [..."あいうえお"],
    base: [
      ..."あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん",
    ],
  },
  {
    name: "katakana",
    vowels: [..."アイウエオ"],
    base: [
      ..."アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン",
    ],
  },
];

describe("stroke-order asset", () => {
  for (const { name, vowels, base } of SCRIPTS) {
    test(`all 46 base ${name} are present`, () => {
      assert.equal(base.length, 46);
      const missing = base.filter((g) => !lookup(g));
      assert.deepEqual(missing, [], `${name} missing from ingest: ${missing.join(" ")}`);
    });

    test(`${name} vowels load with ordered strokes and aligned number labels`, () => {
      for (const v of vowels) {
        const entry = lookup(v);
        assert.ok(entry, `missing ${v}`);
        // Real strokes: at least one, every one a non-empty SVG path starting M.
        assert.ok(entry.strokes.length >= 1, `${v} has no strokes`);
        for (const d of entry.strokes) {
          assert.equal(typeof d, "string");
          assert.match(d, /^M/, `${v} stroke isn't a path: ${d.slice(0, 12)}`);
        }
        // One number label per stroke, each an [x, y] pair on the 109 grid.
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${v}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
        for (const [x, y] of entry.numbers) {
          assert.ok(x >= 0 && x <= 109 && y >= 0 && y <= 109, `${v} label off-grid`);
        }
      }
    });

    test(`every ${name} entry has one label per stroke`, () => {
      for (const g of base) {
        const entry = lookup(g)!;
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${g}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
      }
    });
  }

  test("known stroke counts are right", () => {
    // Hand-counted against the glyphs themselves; a wrong count means the
    // ingest picked up the wrong character or dropped a path.
    const counts: Record<string, number> = {
      あ: 3, し: 1,
      ア: 2, イ: 2, ン: 2, ヲ: 3, ノ: 1, フ: 1, ホ: 4, ネ: 4,
    };
    for (const [g, n] of Object.entries(counts)) {
      assert.equal(lookup(g)!.strokes.length, n, `${g} should be ${n} strokes`);
    }
  });

  test("a glyph with no data degrades to null, not a throw", () => {
    // A kanji nobody teaches isn't ingested — the loader returns null and the
    // section falls back to the whole-shape view.
    assert.equal(lookup("龘"), null); // a non-jōyō kanji
    assert.equal(lookup(""), null); // the collapsed sentinel
  });
});

// SAK-72 Part A: scripts/ingest/kanjivg.mjs's SETS now fetches the 50
// dakuten/handakuten glyphs too (が…ぽ, ガ…ポ), appended after each script's
// base 46. Derived from DAKUTEN_ROWS, exactly like the ingest script itself —
// see that file's `dakutenGlyphs` — so this can never drift from "every
// glyph the app calls dakuten/handakuten" even if a row is added later.
describe("dakuten/handakuten stroke coverage (SAK-72)", () => {
  function dakutenGlyphs(setId: string): string[] {
    return DAKUTEN_ROWS.filter((r) => r.setId === setId).flatMap((r) =>
      r.pairs.map(([, converted]) => converted),
    );
  }

  test("all 25 dakuten/handakuten hiragana and 25 katakana glyphs are present", () => {
    for (const setId of ["hiragana", "katakana"]) {
      const glyphs = dakutenGlyphs(setId);
      assert.equal(glyphs.length, 25, `${setId} should teach 25 dakuten/handakuten glyphs`);
      const missing = glyphs.filter((g) => !lookup(g));
      assert.deepEqual(missing, [], `${setId} missing from ingest: ${missing.join(" ")}`);
    }
  });

  test("every dakuten/handakuten glyph has real, ordered strokes with a plausible count", () => {
    for (const setId of ["hiragana", "katakana"]) {
      for (const g of dakutenGlyphs(setId)) {
        const entry = lookup(g);
        assert.ok(entry, `missing stroke data for ${g}`);
        // A real diagram: at least one base stroke plus at least one mark
        // stroke (the smallest real case is ぴ: ひ's 1 + the handakuten
        // circle's 1 = 2), so this can't quietly pass on a glyph that
        // resolved to nothing, or to just the mark alone.
        assert.ok(entry.strokes.length >= 2, `${g} has an implausibly low stroke count (${entry.strokes.length})`);
        for (const d of entry.strokes) {
          assert.equal(typeof d, "string");
          assert.match(d, /^[Mm]/, `${g} stroke isn't a path: ${d.slice(0, 12)}`);
        }
        assert.equal(
          entry.numbers.length,
          entry.strokes.length,
          `${g}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
        );
        for (const [x, y] of entry.numbers) {
          assert.ok(x >= 0 && x <= 109 && y >= 0 && y <= 109, `${g} label off-grid`);
        }
      }
    }
  });

  test("a derived glyph carries MORE strokes than its own base — the mark is really drawn", () => {
    // が = か (3 strokes) + the dakuten mark (2 strokes) = 5. This is the
    // concrete check that the ingest picked up が's OWN digitized entry —
    // base strokes plus mark strokes — rather than silently reusing the
    // base's data or resolving to some other glyph.
    const pairs: [string, string][] = [
      ["か", "が"],
      ["は", "ば"],
      ["は", "ぱ"],
      ["カ", "ガ"],
      ["ハ", "バ"],
      ["ハ", "パ"],
    ];
    for (const [base, derived] of pairs) {
      const baseEntry = lookup(base)!;
      const derivedEntry = lookup(derived)!;
      assert.ok(
        derivedEntry.strokes.length > baseEntry.strokes.length,
        `${derived} (${derivedEntry.strokes.length}) should have more strokes than its base ${base} (${baseEntry.strokes.length})`,
      );
    }
  });

  test("scriptOf resolves every dakuten/handakuten glyph to its script asset (no code change needed)", () => {
    for (const setId of ["hiragana", "katakana"] as const) {
      for (const g of dakutenGlyphs(setId)) {
        assert.equal(scriptOf(g), setId, `${g} should resolve to the ${setId} asset`);
      }
    }
  });
});

// SAK-72 Part B: scripts/ingest/kanjivg.mjs's SETS now fetches the 6 small
// yōon kana too (ゃゅょ, ャュョ), appended after each script's 46 base + 25
// dakuten/handakuten glyphs — same derived-not-typed source as Part A's
// dakutenGlyphs, but off SMALL_TO_FULL_HIRAGANA's keys (kana-family.ts), the
// one place "the taught small kana" is named.
describe("small yōon kana stroke coverage (SAK-72 Part B)", () => {
  const KATAKANA_OFFSET = 0x60;

  function smallYoonGlyphs(setId: string): string[] {
    const hiragana = Object.keys(SMALL_TO_FULL_HIRAGANA);
    return setId === "hiragana"
      ? hiragana
      : hiragana.map((g) => String.fromCodePoint(g.codePointAt(0)! + KATAKANA_OFFSET));
  }

  test("all 3 small hiragana and 3 small katakana kana are present, as their own single-glyph entries", () => {
    for (const setId of ["hiragana", "katakana"]) {
      const glyphs = smallYoonGlyphs(setId);
      assert.equal(glyphs.length, 3, `${setId} should teach 3 small yōon kana`);
      const missing = glyphs.filter((g) => !lookup(g));
      assert.deepEqual(missing, [], `${setId} missing from ingest: ${missing.join(" ")}`);
    }
  });

  test("every small kana has real, ordered strokes with one label each, and scriptOf resolves it like any single glyph", () => {
    for (const setId of ["hiragana", "katakana"] as const) {
      for (const g of smallYoonGlyphs(setId)) {
        const entry = lookup(g);
        assert.ok(entry, `missing stroke data for ${g}`);
        assert.ok(entry.strokes.length >= 1, `${g} has no strokes`);
        for (const d of entry.strokes) {
          assert.match(d, /^[Mm]/, `${g} stroke isn't a path: ${d.slice(0, 12)}`);
        }
        assert.equal(entry.numbers.length, entry.strokes.length, `${g}: label/stroke count mismatch`);
        // Ingested as an ordinary single-codepoint glyph — same asset, same
        // lookup as き or が. scriptOf itself carries no yōon-specific branch;
        // composing two glyphs is strokes.ts's job (composeGlyphStrokes),
        // exercised below.
        assert.equal(scriptOf(g), setId, `${g} should resolve to the ${setId} asset like any base kana`);
      }
    }
  });
});

describe("composeGlyphStrokes (SAK-72 Part B)", () => {
  function real(glyph: string): { strokes: string[]; numbers: [number, number][] } {
    const entry = lookup(glyph);
    assert.ok(entry, `missing ingested stroke data for ${glyph} — run scripts/ingest/kanjivg.mjs`);
    return entry;
  }

  const PAIRS: [string, string, string][] = [
    ["き", "ゃ", "きゃ"],
    ["し", "ゅ", "しゅ"],
    ["キ", "ャ", "キャ"],
  ];

  test("composed stroke count is exactly base + small — nothing dropped, nothing duplicated", () => {
    for (const [base, small, combo] of PAIRS) {
      const b = real(base);
      const s = real(small);
      const composed = composeGlyphStrokes(b, s);
      assert.equal(
        composed.strokes.length,
        b.strokes.length + s.strokes.length,
        `${combo}: composed stroke count`,
      );
      assert.equal(composed.numbers.length, composed.strokes.length);
    }
  });

  test("the base glyph's own strokes are carried through completely unchanged", () => {
    for (const [base, small] of PAIRS) {
      const b = real(base);
      const s = real(small);
      const composed = composeGlyphStrokes(b, s);
      assert.deepEqual(
        composed.strokes.slice(0, b.strokes.length),
        b.strokes,
        `${base}'s own strokes must be byte-for-byte identical inside the composite`,
      );
    }
  });

  test("the small glyph's strokes are genuinely TRANSFORMED, not just concatenated raw", () => {
    for (const [base, small] of PAIRS) {
      const b = real(base);
      const s = real(small);
      const composed = composeGlyphStrokes(b, s);
      const composedSmall = composed.strokes.slice(b.strokes.length);
      assert.notDeepEqual(composedSmall, s.strokes, "small strokes must differ from their raw form");
    }
  });

  test("the composed small strokes are SMALLER and sit in the grid's bottom-right corner", () => {
    // Resolved with pathBBox — the real absolute extent, not a naive read of
    // every raw number in the `d` string (most of which are RELATIVE deltas,
    // not coordinates, and can be negative or exceed the grid on their own).
    for (const [base, small] of PAIRS) {
      const b = real(base);
      const s = real(small);
      const composed = composeGlyphStrokes(b, s);
      const composedSmall = composed.strokes.slice(b.strokes.length);
      const rawSmallBBox = union(s.strokes.map(pathBBox));
      const composedSmallBBox = union(composedSmall.map(pathBBox));

      // Genuinely smaller than its own standalone (full-grid) rendering.
      const rawSize = Math.max(
        rawSmallBBox.xmax - rawSmallBBox.xmin,
        rawSmallBBox.ymax - rawSmallBBox.ymin,
      );
      const composedSize = Math.max(
        composedSmallBBox.xmax - composedSmallBBox.xmin,
        composedSmallBBox.ymax - composedSmallBBox.ymin,
      );
      assert.ok(composedSize < rawSize, `${small}: composed (${composedSize}) should be smaller than raw (${rawSize})`);

      // On the grid, and anchored to the bottom-right corner (within the
      // margin composeGlyphStrokes uses).
      assert.ok(composedSmallBBox.xmax <= STROKE_GRID, `${small}: composed xmax on-grid`);
      assert.ok(composedSmallBBox.ymax <= STROKE_GRID, `${small}: composed ymax on-grid`);
      assert.ok(composedSmallBBox.xmax > STROKE_GRID / 2, `${small}: composed strokes reach the right half`);
      assert.ok(composedSmallBBox.ymax > STROKE_GRID / 2, `${small}: composed strokes reach the bottom half`);
    }
  });

  test("composing does not mutate the inputs — a base's own single-glyph rendering is unaffected", () => {
    const b = real("き");
    const s = real("ゃ");
    const beforeBase = JSON.stringify(b);
    const beforeSmall = JSON.stringify(s);
    composeGlyphStrokes(b, s);
    assert.equal(JSON.stringify(b), beforeBase, "base data must not be mutated");
    assert.equal(JSON.stringify(s), beforeSmall, "small data must not be mutated");
  });
});

describe("kanji chunks", () => {
  test("every jōyō kanji is in the chunk its codepoint names", () => {
    // Not just "present somewhere": present in the ONE file the loader will
    // fetch for it. A glyph in the wrong chunk is invisible at runtime.
    const missing: string[] = [];
    for (const { c } of KANJI) {
      const entry = CHUNKS[c.codePointAt(0)! % KANJI_CHUNKS][c];
      if (!entry) missing.push(c);
    }
    assert.deepEqual(missing, [], `not in their chunk: ${missing.join(" ")}`);
    assert.equal(KANJI.length, 2136);
  });

  test("every kanji entry has real ordered strokes, one label each", () => {
    for (const { c } of KANJI) {
      const entry = lookup(c)!;
      assert.ok(entry.strokes.length >= 1, `${c} has no strokes`);
      // `M` or `m`: KanjiVG mostly emits an absolute moveto, but a handful
      // (偏 慣 掛 貫 頃) start relative. Both are valid SVG and the renderer
      // hands the `d` straight to the browser, so the test accepts either
      // rather than the absolute-only form the kana happen to use.
      assert.match(entry.strokes[0], /^[Mm]/, `${c} stroke isn't a path`);
      assert.equal(
        entry.numbers.length,
        entry.strokes.length,
        `${c}: ${entry.numbers.length} labels for ${entry.strokes.length} strokes`,
      );
    }
  });

  test("KANJIDIC2's stroke count agrees with KanjiVG's, bar 9 known cases", () => {
    // Two INDEPENDENT sources for the same fact, which is what makes this a
    // real check: a chunk keyed to the wrong character would disagree on the
    // count for hundreds of glyphs, so this is the test that catches a
    // mis-keyed ingest.
    //
    // Nine genuinely disagree, and they are upstream editorial differences, not
    // ingest errors — each SVG's own kvg:element names the character we asked
    // for. Eight are 2010 jōyō additions that KanjiVG draws with the PRINTED
    // component form, one stroke more than KANJIDIC2 counts for the handwritten
    // one (謎 賭 遜 遡 with the two-dot shinnyō, 餅 餌 with 𩙿 for 飠, plus 僅
    // 葛). 牙 goes the other way: KanjiVG draws 4, KANJIDIC2's primary count is
    // 5. Pinned by name so a TENTH disagreement fails this test rather than
    // quietly joining the list.
    const disagree = KANJI.filter(({ c, strokes }) => lookup(c)!.strokes.length !== strokes)
      .map(({ c }) => c)
      .sort();
    assert.deepEqual(disagree, [..."僅牙葛謎賭遜遡餅餌"].sort());
  });

  test("JOUYOU lists exactly the kanji the app teaches", () => {
    // The membership string gates every kanji fetch, so a drift between it and
    // the app's kanji set is either a wasted download or a missing diagram.
    assert.deepEqual([...JOUYOU].sort(), KANJI.map((k) => k.c).sort());
  });

  test("no chunk is big enough to hurt: 48 files, none over 96KB", () => {
    // The bound the split exists to hold. 2.2MB over 48 files is ~46KB each and
    // the largest is ~58KB; 96KB is headroom for a re-ingest, not a target. If
    // this trips, the chunk COUNT needs raising, not the bound.
    const sizes = CHUNKS.map((_, n) =>
      statSync(
        fileURLToPath(
          new URL(`../data/generated/strokes/${chunkName(n)}.json`, import.meta.url),
        ),
      ).size,
    );
    assert.equal(sizes.length, 48);
    const biggest = Math.max(...sizes);
    assert.ok(biggest <= 96 * 1024, `largest chunk is ${(biggest / 1024).toFixed(1)}KB`);
    // And evenly enough spread that no chunk is an outlier: the modulo is only
    // worth using over a range split because it distributes.
    assert.ok(
      biggest <= 2 * Math.min(...sizes),
      `chunks are lopsided: ${(Math.min(...sizes) / 1024).toFixed(1)}KB to ${(biggest / 1024).toFixed(1)}KB`,
    );
  });
});

describe("radical stroke coverage", () => {
  // The whole point of the radical ingest: a non-jōyō radical (禾) and a variant
  // form (氵) — neither a jōyō kanji — now draw a real diagram instead of the
  // count-only fallback. Concrete pins so a future run dropping them fails here.
  test("禾 and 氵 resolve to their chunk and have real, aligned strokes", () => {
    for (const g of ["禾", "氵"]) {
      assert.equal(scriptOf(g), `kanji-${g.codePointAt(0)! % KANJI_CHUNKS}`);
      const entry = lookup(g);
      assert.ok(entry && entry.strokes.length >= 1, `${g} has no strokes`);
      assert.match(entry!.strokes[0], /^[Mm]/, `${g} stroke isn't a path`);
      assert.equal(
        entry!.numbers.length,
        entry!.strokes.length,
        `${g}: ${entry!.numbers.length} labels for ${entry!.strokes.length} strokes`,
      );
    }
  });

  test("RADICAL_GLYPHS is non-jōyō only, and every one is in the chunk it names", () => {
    // The second membership string must not overlap JOUYOU (that would blur what
    // JOUYOU means), and every glyph it lists must actually be fetchable in the
    // ONE chunk its codepoint points at — else the loader names a file that misses.
    const jset = new Set([...JOUYOU]);
    const overlap: string[] = [];
    const missing: string[] = [];
    for (const g of [...RADICAL_GLYPHS]) {
      if (jset.has(g)) overlap.push(g);
      if (!CHUNKS[g.codePointAt(0)! % KANJI_CHUNKS][g]) missing.push(g);
    }
    assert.deepEqual(overlap, [], `also in JOUYOU: ${overlap.join(" ")}`);
    assert.deepEqual(missing, [], `not in their chunk: ${missing.join(" ")}`);
  });
});

describe("scriptOf: which asset to fetch, if any", () => {
  test("a single kana picks its own script's asset", () => {
    assert.equal(scriptOf("あ"), "hiragana");
    assert.equal(scriptOf("ん"), "hiragana");
    assert.equal(scriptOf("ア"), "katakana");
    assert.equal(scriptOf("ヲ"), "katakana");
  });

  test("a single jōyō kanji picks the one chunk it lives in", () => {
    for (const c of ["水", "生", "明", "一", "𠮟"]) {
      assert.equal(scriptOf(c), `kanji-${c.codePointAt(0)! % KANJI_CHUNKS}`);
    }
    // And it resolves for ALL of them, not just the handful spelled out.
    const unresolved = KANJI.filter(({ c }) => scriptOf(c) === null);
    assert.deepEqual(unresolved.map((k) => k.c), []);
  });

  test("nothing is fetched for a glyph with no ingested asset", () => {
    // A kanji outside the jōyō set is in no chunk, so naming one for it would
    // buy a download that must miss. It settles to null instead.
    assert.equal(scriptOf("龘"), null);
    assert.equal(scriptOf("怱"), null);
    assert.equal(scriptOf(""), null); // the collapsed-section sentinel
    assert.equal(scriptOf("〜"), null); // punctuation
    assert.equal(scriptOf("A"), null);
  });

  // THE BUG THIS PINS: これ starts with hiragana, so a first-codepoint-only
  // test said "hiragana" and the whole hiragana map was fetched over the
  // network — and then missed, because the map is keyed by ONE character.
  // A download that could not possibly succeed. Multi-character strings must
  // settle to null WITHOUT asking for an asset.
  test("a multi-character string never asks for an asset", () => {
    for (const s of ["これ", "がっこう", "学生", "〜てから", "サッカー"]) {
      assert.equal(scriptOf(s), null, `${s} must not trigger a stroke fetch`);
      // And the reason it must not: the asset could never have answered it.
      assert.equal(lookup(s), null, `${s} is not a key in the stroke map`);
    }
  });

  test("a glyph outside the BMP still counts as one character", () => {
    // Counted in codepoints, not UTF-16 units: a surrogate pair is one glyph,
    // and must not be rejected as if it were two characters.
    const surrogatePair = "\u{20BB7}"; // 𠮷, a kanji — null for lack of data,
    assert.equal(surrogatePair.length, 2); // not for being "two characters".
    assert.equal([...surrogatePair].length, 1);
    assert.equal(scriptOf(surrogatePair), null);
  });
});
