// The invariant this file exists to hold: NO SHIPPED EXAMPLE LACKS ITS OWN
// PATTERN.
//
// The corpus is regenerated by a Python script that cannot run in CI (it needs
// the Tatoeba dump and fugashi/unidic-lite), so nothing stops someone re-cutting
// it on their laptop and committing the raw output. These tests are what makes
// that fail loudly: they re-run the audit against the shipped file rather than
// trusting that it was run.

import assert from "node:assert/strict";
import { describe, test } from "node:test";

import { CORPUS, CORPUS_META, examplesFor } from "./corpus.ts";
import { AUDITED, confoundFor } from "./corpus-audit.ts";

describe("no shipped example lacks its own pattern", () => {
  test("the audit finds nothing left to drop", () => {
    const guilty: string[] = [];
    for (const ex of CORPUS) {
      for (const p of ex.p) {
        const why = confoundFor(ex, p);
        if (why) guilty.push(`${ex.id} ${ex.jp} filed as ${p}: ${why}`);
      }
    }
    assert.deepEqual(
      guilty.slice(0, 10),
      [],
      `${guilty.length} confounded examples are shipped. Run: node scripts/audit-corpus.ts`,
    );
  });

  test("the meta records that the audit ran", () => {
    // A re-cut of grammar.py writes the meta WITHOUT this block. That is the
    // signal that the audit was skipped, and it is worth more than the counts.
    assert.ok(CORPUS_META.audit, "meta has no audit block — was audit-corpus.ts skipped?");
    assert.equal(CORPUS_META.audit.rules, "src/data/grammar/corpus-audit.ts");
    assert.deepEqual([...CORPUS_META.audit.patterns].sort(), [...AUDITED].sort());
  });

  test("every sentence still claims at least one pattern", () => {
    // The audit removes claims, and a sentence that loses all of them must
    // leave rather than sit in the file untagged.
    for (const ex of CORPUS) assert.ok(ex.p.length > 0, `${ex.id} has no patterns`);
  });

  test("meta.perPattern is the file's real content, not the cap", () => {
    const actual: Record<string, number> = {};
    for (const ex of CORPUS) for (const p of ex.p) actual[p] = (actual[p] ?? 0) + 1;
    for (const [p, n] of Object.entries(CORPUS_META.perPattern)) {
      assert.equal(n, actual[p] ?? 0, `meta says ${p}=${n}, the file holds ${actual[p] ?? 0}`);
    }
    assert.equal(CORPUS_META.counts.kept, CORPUS.length);
  });
});

describe("the sentences that made this a P0 are gone", () => {
  // Both were served live as examples of 〜ので ("because"). Neither contains
  // ので and neither is causal; the first has no other pattern, so the whole
  // sentence left, and the second survives on its `wo` claim alone.
  const knownBad = ["ログアウトするんじゃなかったよ。", "ここを動くんじゃないぞ。"];

  test("no 〜ので example is one of them", () => {
    const jp = new Set(examplesFor("node").map((e) => e.jp));
    for (const bad of knownBad) assert.ok(!jp.has(bad), `still filed under node: ${bad}`);
  });

  test("every 〜ので example contains ので", () => {
    for (const ex of examplesFor("node")) {
      assert.ok(ex.jp.includes("ので"), `${ex.id} ${ex.jp} has no ので`);
    }
  });

  test("no 〜ば example is really an obligation", () => {
    for (const ex of examplesFor("ba")) {
      const [s, e] = ex.sp["ba"]!;
      assert.ok(!ex.jp.slice(s, e).includes("なければ"), `${ex.id} ${ex.jp} is なければ`);
    }
  });
});

describe("coverage after the audit is recorded, not assumed", () => {
  /**
   * WHAT SURVIVED, PINNED.
   *
   * These are not aspirations — they are the measured post-audit counts, here
   * so that a change to the corpus or the audit rules has to state what it did
   * to teaching coverage instead of moving a number quietly. Update them
   * deliberately, with the new figure in the commit message.
   *
   * `node` is the one to watch: 214 -> 89. Still enough to drill from, but it
   * lost 58% of its supply, which is the argument for fixing the ので signature
   * in grammar.py rather than only filtering after it.
   */
  const SURVIVED: Readonly<Record<string, number>> = {
    ba: 257,
    "kara-reason": 213,
    "made-ni": 85,
    nikui: 63,
    node: 89,
    "ta-tokoro": 139,
  };

  for (const [p, n] of Object.entries(SURVIVED)) {
    test(`${p} still has ${n} examples`, () => {
      assert.equal(examplesFor(p).length, n);
    });
  }

  test("no audited pattern was quietly emptied", () => {
    // The failure mode this guards is a rule that is too aggressive: an audit
    // that leaves a pattern with nothing is a pattern the app can no longer
    // teach, and that must be a decision, not a side effect.
    for (const p of AUDITED) {
      assert.ok(examplesFor(p).length >= 20, `${p} fell to ${examplesFor(p).length}`);
    }
  });

  test("the only patterns with no examples at all are the known ones", () => {
    // ta-ato-de is genuinely scarce in Tatoeba (0 raw matches survived the
    // ingest filters); the rest are recipes deliberately given no signature.
    // Anything NEW here is a regression, whatever produced it.
    const empty = Object.entries(CORPUS_META.perPattern)
      .filter(([, n]) => n === 0)
      .map(([p]) => p)
      .sort();
    assert.deepEqual(empty, ["ta-ato-de"]);
  });
});
