// The example corpus: 8,547 Tatoeba sentences, morphologically matched to the
// recipes in recipes.ts. Generated by scripts/ingest/grammar.py; see that file
// for how, and for what the filter does NOT remove. Then audited by
// scripts/audit-corpus.ts, which is the reason the number is 8,547 and not the
// 8,689 that script prints — see corpus-audit.ts for what came out and why.
//
// READ THIS BEFORE TRUSTING A SENTENCE FROM HERE
// ==============================================
// Tatoeba is the weakest source in this design, and grammar is the ONLY
// subject standing on it. Kanji and vocabulary sit on curated JMdict and
// KANJIDIC2; this sits on a community wiki. Specifically:
//
//   - NOT level-vetted. There is no N5 flag in Tatoeba and this file does not
//     invent one. A sentence here matched an N5 PATTERN. That is all it means.
//   - Contains ungrammatical sentences. 彼女は余暇を人形を作って過ごす。 has a
//     double を and is in the corpus today. Nothing here catches that.
//   - Register skews literary and proverbial. The <=14-token filter and the
//     shortest-first cap pull against this; they do not fix it.
//   - The tag means "this sentence contains this pattern", never "this is a
//     GOOD example of it". The audit removed sentences that did not contain
//     their pattern at all; it did not, and cannot, rank the rest.
//
// So a sentence from here is "a real sentence a human wrote, which another
// human translated". It is NOT "a good example", and the app must not imply
// otherwise.
//
// ATTRIBUTION: Tatoeba is CC BY 2.0 FR. See src/data/attribution.ts.

import corpusJson from "../generated/grammar-corpus.json" with { type: "json" };
import metaJson from "../generated/grammar-corpus-meta.json" with { type: "json" };
import { AUTHORED } from "./authored";

/** One example sentence. Field names are short because 8,689 of these ship. */
export interface Example {
  /** Tatoeba sentence id — the permalink, and the attribution. */
  readonly id: number;
  readonly jp: string;
  /** A HUMAN translation, directly linked. Never machine-translated. */
  readonly en: string;
  /** Token count, excluding punctuation. */
  readonly n: number;
  /**
   * The CONTENT lemmas (nouns, verbs, adjectives, adverbs) in this sentence.
   *
   * Particles and auxiliaries are excluded on purpose: anyone who has met a
   * verb has met は and を, so counting them pushes every sentence toward 100%
   * coverage and the knownness filter stops filtering.
   */
  readonly v: readonly string[];
  /** Recipe ids this sentence matched. */
  readonly p: readonly string[];
  /**
   * Per-recipe blank span: [startChar, endChar, hostDictionaryForm].
   *
   * The span COVERS THE HOST VERB, not just the suffix — 亡くなってから blanks
   * as a whole, because a blank starting after 亡くなっ has already told you
   * the answer takes the て-form. `hostDictionaryForm` is the prompt word
   * (亡くなる), so the question is "which pattern goes here", not "which
   * suffix", which is the question worth asking.
   *
   * null host for the handful of signatures with no host anchor (そう, たら).
   */
  readonly sp: Readonly<Record<string, readonly [number, number, string | null]>>;
}

export const CORPUS: readonly Example[] = corpusJson as readonly Example[];

export interface CorpusMeta {
  readonly generated: string;
  readonly source: string;
  readonly maxTokens: number;
  readonly minOwnerSentences: number;
  readonly perPatternCap: number;
  readonly counts: { readonly japanese: number; readonly withEnglish: number; readonly kept: number };
  /**
   * How many examples of each pattern the shipped file ACTUALLY holds, after
   * the confound audit. Zero is a key, not a missing key — see `SCARCE`.
   *
   * This is not what grammar.py wrote here. It wrote min(owned, cap), which
   * read 200 for 33 patterns while the file held 2,029 `wo` examples: the cap
   * counts sentences SELECTED for a pattern, and a sentence selected for one
   * pattern brings its other tags in with it. scripts/audit-corpus.ts replaces
   * it with the true count, because "how much is there to teach from" is the
   * only question this field is ever asked.
   */
  readonly perPattern: Readonly<Record<string, number>>;
  /** The tagger's own filtered count, before its cap AND before the audit. */
  readonly perPatternBeforeCap: Readonly<Record<string, number>>;
  /** Recipes deliberately not matched, and why. Rendered, not hidden. */
  readonly noSignature: Readonly<Record<string, string>>;
  /**
   * The confound audit that produced this file. Absent means a re-cut of
   * grammar.py wrote the meta and the audit was never re-run — which a test
   * asserts against, because that file's `node` is 58% wrong.
   * See src/data/grammar/corpus-audit.ts.
   */
  readonly audit: {
    readonly by: string;
    readonly rules: string;
    /** Patterns the audit has rules for. */
    readonly patterns: readonly string[];
    /** Pattern claims removed. */
    readonly droppedExamples: number;
    /** Sentences removed entirely, having had no surviving claim. */
    readonly droppedSentences: number;
  };
}

export const CORPUS_META = metaJson as CorpusMeta;

const BY_PATTERN: ReadonlyMap<string, Example[]> = groupByPattern();

function groupByPattern(): Map<string, Example[]> {
  const map = new Map<string, Example[]>();
  // The corpus, then the hand-authored lane (authored.ts) — the few recipes
  // Tatoeba cannot supply. Both group the same way, so examplesFor treats an
  // authored わけだ sentence exactly like a tagged one and it DRILLS. Only this
  // grouping sees AUTHORED; the CORPUS array stays pure so every count invariant
  // measures the ingest alone.
  for (const ex of [...CORPUS, ...AUTHORED]) {
    for (const p of ex.p) {
      const list = map.get(p);
      if (list) list.push(ex);
      else map.set(p, [ex]);
    }
  }
  return map;
}

/** Every example for a recipe. Empty is a real answer — see `SCARCE`. */
export function examplesFor(recipeId: string): readonly Example[] {
  return BY_PATTERN.get(recipeId) ?? [];
}

/**
 * How much of this sentence's content vocabulary the user knows, 0..1.
 *
 * Computed at RUNTIME and not baked into the artifact, because knownness is
 * per-user and changes every session — freezing one user's progress into a
 * committed JSON would be a category error. `known` is normally the key set of
 * history.facts, resolved to lemmas by the caller.
 *
 * A sentence with no content words scores 1: there is nothing unknown in it.
 */
export function coverage(ex: Example, known: ReadonlySet<string>): number {
  if (ex.v.length === 0) return 1;
  let hit = 0;
  for (const lemma of ex.v) if (known.has(lemma)) hit++;
  return hit / ex.v.length;
}

/** The >=95% known-vocabulary filter from the brief, as a predicate. */
export function isReadable(ex: Example, known: ReadonlySet<string>, floor = 0.95): boolean {
  return coverage(ex, known) >= floor;
}

/**
 * Recipes whose example supply is too thin to drill from, with their count.
 *
 * Two of these were predicted before the corpus was built and both were
 * confirmed by it, which is worth recording:
 *
 *   ta-ato-de   0 (8 raw, none survived the filters). GENUINELY scarce —
 *               learners write 、where a textbook writes で.
 *   tari-tari  26. Structural: the pattern needs TWO verbs, so the token
 *               filter bites hardest exactly here.
 *
 * Both need hand-authored examples. Anything at 0 must not be drilled from
 * the corpus, and the UI should say so rather than showing an empty card.
 */
export const SCARCE: readonly { readonly id: string; readonly n: number }[] = Object.entries(
  CORPUS_META.perPattern,
)
  .filter(([, n]) => n < 20)
  .map(([id, n]) => ({ id, n }))
  .sort((a, b) => a.n - b.n);
