// Forgiving-but-safe matching for TYPED ENGLISH answers.
//
// The base grader (`accepts` in question.ts) compares a typed answer against a
// fact's listed glosses by exact, case- and space-insensitive equality. That is
// right for a Japanese reading and too strict for an English meaning: a JMdict
// gloss carries disambiguating notes the learner cannot know to type, numbers
// are spelled out where a digit is the obvious answer, and a single dropped
// letter should not read as "wrong".
//
// This module adds four deterministic layers, in strict priority of safety.
// The one rule the whole file obeys: it only ever ACCEPTS MORE, and only ever
// against the fact's OWN glosses — it can turn a rejected right answer into a
// pass, and can never turn one fact's wrong answer into another fact's right
// one. There is deliberately no GENERAL synonym model: a benchmark (SAK-53's
// spike) showed a phrase-level fuzzy/embedding approach accepts antonyms.
//
//   1. Curated synonym pool, EXACT MATCH ONLY. A small, precision-filtered,
//      mostly auto-generated (Datamuse, reviewed) list of equivalents for
//      single-word AND short multi-word glosses — "nonexistent" also accepts
//      "absent", "missing" …, "does not exist" also accepts "not existing"
//      — built by scripts/build-en-synonyms.mjs into
//      src/data/generated/en-synonyms.json. See `synonymCandidates` below for
//      why this stays a SEPARATE pool from the layers under it: an entry here
//      is never run through the typo layer, so one bad entry can degrade to
//      "this one string is also accepted", never compound into a worse false
//      positive the way a general synonym-then-fuzz model would.
//   2. Strip parenthetical qualifiers. "line (of text), row, verse" also
//      accepts "line", "row", "verse" — the "(of text)" is JMdict's note and
//      the commas separate independent glosses.
//   3. Digit form of a spelled number. "four (4)" also accepts "4"; "one thing"
//      also accepts "1 thing" and "1". Only digits of number WORDS actually
//      present in the gloss are added, so no wrong answer can pass.
//   4. Length-scaled typo tolerance. An answer within a small Levenshtein
//      distance of a (paren-stripped) gloss passes — tuned so "ting"→"thing"
//      and "teacer"→"teacher" pass but "cat"/"car" and "one"/"two" do not.
//
// EVERYTHING HERE IS ENGLISH-ONLY. The layers run only against glosses that
// contain a Latin letter (`isEnglishGloss`), so a Japanese reading answer — し,
// せんせい — reaches none of them and keeps exact-match grading. That is what
// lets `accepts`, which grades readings too, call this without loosening a kana
// reading into a near-miss. Pure, dependency-free, microseconds.

import { glossCandidates, isEnglishGloss, norm, stripParentheticals, synonymKeyOf, withinTypo } from "@/lib/en-text";

// The layers themselves are in en-text.ts, which has no data behind it, so
// the Sky's browser-side grader can have them without this file's pool
// (SAK-380). Re-exported here because this is where they are documented and
// where callers have always looked for them.
export { digitVariants, glossCandidates, isEnglishGloss, levenshtein, norm, stripParentheticals, synonymKeyOf, typoBudget, withinTypo } from "@/lib/en-text";

import synonymPoolJson from "../../data/generated/en-synonyms.json" with { type: "json" };

/** gloss key → curated equivalent phrasings, exact-match only. Generated by
 * scripts/build-en-synonyms.mjs; see that file's header for how the pool is
 * built (Datamuse rel_syn/ml, filtered) and self-reviewed. */
const SYNONYM_POOL: Readonly<Record<string, readonly string[]>> = synonymPoolJson;

/**
 * Every curated-pool synonym that answers ANY of `answers`, drawn from the
 * SAME fragments layer 2 below checks (the whole gloss, its paren-stripped
 * form, and each comma-separated piece) — so a synonym reaches a fact through
 * exactly the same gloss slicing the rest of this module already trusts, never
 * a looser one. Kept as its own Set, not merged into the layer-2/3 candidate
 * pool: entries here must be compared EXACT-ONLY (see `matchesEnglish`), and
 * merging pools would let the typo layer fuzz a synonym-pool entry too — the
 * exact compounding risk the curated-pool design exists to avoid.
 */
export function synonymCandidates(answers: readonly string[]): Set<string> {
  const out = new Set<string>();
  for (const a of answers) {
    if (!isEnglishGloss(a)) continue;
    const stripped = stripParentheticals(a);
    for (const piece of [a, stripped, ...stripped.split(",")]) {
      const key = synonymKeyOf(piece);
      if (!key) continue;
      const syns = SYNONYM_POOL[key];
      if (!syns) continue;
      for (const s of syns) out.add(s);
    }
  }
  return out;
}

/**
 * Whether `given` matches any of `answers`, forgivingly but safely.
 *
 * Exact (case/space) against EVERY answer first — the unchanged base behaviour,
 * and the only layer a Japanese reading answer ever reaches. Then, for the
 * English answers only, the parenthetical/comma candidates, their digit
 * variants, and finally a length-scaled typo tolerance against each candidate.
 *
 * Order is by safety: a real match wins before any edit-distance guess, and the
 * typo layer is the last resort. Returns as soon as any layer accepts.
 */
export function matchesEnglish(given: string, answers: readonly string[]): boolean {
  const g = norm(given);
  if (!g) return false;

  // Layer 0 — exact against all answers, Japanese readings included.
  for (const a of answers) {
    if (norm(a) === g) return true;
  }

  // Layer 1 — curated synonym pool, EXACT MATCH ONLY, never fuzzed. See
  // `synonymCandidates` for why it is kept out of the layer 2/3 pool below.
  if (synonymCandidates(answers).has(g)) return true;

  // Build the English candidate pool once (layers 2 & 3), then the typo pass.
  const candidates = new Set<string>();
  for (const a of answers) {
    if (!isEnglishGloss(a)) continue;
    for (const c of glossCandidates(a)) candidates.add(c);
  }
  if (candidates.has(g)) return true;

  // Layer 3 — length-scaled typo tolerance, last resort.
  for (const c of candidates) {
    if (withinTypo(g, c)) return true;
  }
  return false;
}
