// The ASSEMBLY corpus: sentences broken into ordered drag pieces, for the
// "build the sentence" question type (task 11).
//
// Generated by scripts/ingest/assembly.py from grammar-corpus.json, re-tokenized
// with fugashi + unidic-lite (the SAME morphological tagger the grammar corpus
// was built with). See that script for the two filters that keep this honest,
// which are the whole reason this can exist beside the never-mark-wrong rule:
//
//   1. Word boundaries come from the tagger, never a hand-rolled guess. A
//      particle rides with its preceding content word (ごはん+を = one piece
//      "ごはんを"), exactly as the approved mockup draws it, so the test is WORD
//      ORDER, never particle choice.
//   2. Only sentences whose piece order is GENUINELY FIXED survive. A sentence
//      that admits more than one natural order (two case-marked arguments that
//      scramble, coordinate clauses that reorder) is DROPPED, not graded — see
//      `single_order` in the ingest script. 596 of 8,547 survive; the small
//      honest set is the point.
//
// The known-words gate (`pickAssembly`) is applied at RUNTIME, per learner,
// exactly like the selection corpus's readability gate: an item is offered only
// when every content lemma in it is a word the learner knows.

import assemblyJson from "./generated/assembly-corpus.json" with { type: "json" };
import { VOCAB } from "./vocab.ts";
import { patternMeaningFactId } from "./grammar/index.ts";
import { lemmaKnown } from "../lib/grammar/readable.ts";
import { factInfo } from "../lib/facts.ts";
import type { Rng } from "../lib/grammar/vehicles.ts";
import type { FactId, HistoryFile } from "../types/index.ts";

/** One draggable piece: its surface text, and the dictionary form of its head
 * content word (for a meaning hint), or null when the piece has no content head
 * (a bare adverb/particle cluster). */
export interface AssemblyPiece {
  readonly t: string;
  readonly h: string | null;
}

/** One assembly item — a sentence to rebuild from its pieces. */
export interface AssemblyItem {
  /** Tatoeba sentence id, for attribution and reporting a bad item. */
  readonly id: number;
  /** The human English translation — the prompt. */
  readonly en: string;
  /** The canonical sentence, pieces joined. */
  readonly jp: string;
  /** The pieces IN CANONICAL ORDER. The one accepted order is this sequence. */
  readonly pieces: readonly AssemblyPiece[];
  /** Content lemmas, for the known-words gate. */
  readonly v: readonly string[];
  /** The grammar patterns this sentence matched — the facts a correct assembly
   * credits. See `assemblyFacts`. */
  readonly p: readonly string[];
}

export const ASSEMBLY: readonly AssemblyItem[] = assemblyJson as readonly AssemblyItem[];

/** keb OR reb → glosses, built once, for the per-piece meaning hint. */
const GLOSS_BY_SPELLING: ReadonlyMap<string, readonly string[]> = (() => {
  const map = new Map<string, readonly string[]>();
  for (const w of VOCAB) {
    for (const spelling of new Set([w.keb, w.reb])) {
      if (!map.has(spelling)) map.set(spelling, w.glosses);
    }
  }
  return map;
})();

/**
 * The meaning hint for a piece — the first gloss of its head content word, or
 * null when the piece has no content head or the word is not in the vocabulary.
 *
 * DRAFT COPY: this glosses only the head word (ごはんを → "meal"), not the whole
 * piece with its particle. It is honest and one tap away, per the mockup, but
 * the exact wording is not yet reviewed.
 */
export function pieceHint(piece: AssemblyPiece): string | null {
  if (!piece.h) return null;
  return GLOSS_BY_SPELLING.get(piece.h)?.[0] ?? null;
}

/**
 * The canonical order for an item — the one accepted answer.
 */
export function canonicalOrder(item: AssemblyItem): readonly string[] {
  return item.pieces.map((p) => p.t);
}

/**
 * Does this order of piece surfaces grade CORRECT?
 *
 * There is exactly one accepted order: the canonical one. Word order is the
 * whole question, so this is a straight sequence comparison — no particle
 * leniency to get wrong, because particles ride inside the pieces.
 */
export function gradeAssembly(item: AssemblyItem, order: readonly string[]): boolean {
  const canon = canonicalOrder(item);
  if (order.length !== canon.length) return false;
  return order.every((t, i) => t === canon[i]);
}

/**
 * The facts a correct assembly credits — the MEANING fact of each pattern the
 * sentence uses, filtered to those the registry actually has. Placing a pattern
 * correctly in a whole sentence is evidence about where it goes, which is the
 * standing the selection cloze already moves; assembly is a second way to
 * exercise the same facts rather than a new kind of score.
 */
export function assemblyFacts(item: AssemblyItem): FactId[] {
  return item.p.map(patternMeaningFactId).filter((f) => factInfo(f));
}

/**
 * Every distinct fact represented by assembly items the learner can currently
 * read. Used to gate and label sentence-ordering drills started from Learn.
 */
export function readableAssemblyFacts(history: HistoryFile): FactId[] {
  const out = new Set<FactId>();
  for (const item of readableAssembly(history)) {
    for (const fact of assemblyFacts(item)) out.add(fact);
  }
  return [...out];
}

/**
 * Can the learner read this item — every content lemma known?
 */
export function assemblyReadable(item: AssemblyItem, history: HistoryFile): boolean {
  return item.v.every((lemma) => lemmaKnown(lemma, history));
}

/**
 * Every assembly item the learner can read right now.
 */
export function readableAssembly(history: HistoryFile): readonly AssemblyItem[] {
  return ASSEMBLY.filter((it) => assemblyReadable(it, history));
}

/**
 * One structural tier in the sentence-ordering track — a named sentence type
 * (e.g. "Conditional sentences") defined by the grammar pattern IDs that tag
 * its sentences in the assembly corpus.
 *
 * Tiers are ordered by pedagogical complexity: Simple first, then Conditional,
 * Causal, Obligation and so on. The learner sees them as sentence STRUCTURE
 * lessons, not grammar lessons — the pattern IDs are the engine's internal
 * classification, never shown.
 */
export interface AssemblyTier {
  readonly id: string;
  /** Learner-visible name, shown on the lesson card. */
  readonly label: string;
  /** Assembly corpus pattern IDs (`item.p`) that define this tier. A sentence
   * belongs to the FIRST tier whose pattern set intersects its own pattern
   * list, provided no later-tier pattern also appears (see
   * `readableAssemblyForTier`). */
  readonly patterns: readonly string[];
  /** Minimum number of readable sentences required for the tier to unlock.
   * Below this, the learner cannot do a meaningful drill, so the tier is
   * skipped rather than shown as locked. */
  readonly minReadable: number;
  /**
   * Grammar pattern IDs that must have been taught in the grammar track before
   * this tier unlocks. At least ONE must be learned (seen, claimed or tested).
   *
   * Empty for the simple tier — its patterns are structural particles that the
   * grammar track never teaches as lessons. For all other tiers the prereqs
   * are the patterns that describe the sentence structure this tier practices,
   * so the learner knows what the pattern means before they practise placing it.
   */
  readonly grammarPrereqs: readonly string[];
}

/**
 * The ordered sentence-structure tiers the sentence-ordering track teaches.
 *
 * Each tier unlocks independently once the learner has enough vocabulary to
 * read its sentences — no grammar fact state is consulted here. The tiers are
 * ordered from structurally simplest to most complex, so the learner always
 * encounters simple particle-marked SOV sentences before conditional clauses,
 * before causal connectives, and so on.
 */
export const SENTENCE_ORDERING_TIERS: readonly AssemblyTier[] = [
  {
    id: "simple",
    label: "Simple sentences",
    patterns: ["wo", "e", "made", "made-ni", "dake", "kara-source"],
    minReadable: 3,
    // Particles are structural markers, never taught as grammar lessons.
    grammarPrereqs: [],
  },
  {
    id: "conditional",
    label: "Conditional sentences",
    patterns: ["tara", "ba", "nara"],
    minReadable: 3,
    grammarPrereqs: ["tara", "ba", "nara"],
  },
  {
    id: "causal",
    label: "Because / so",
    patterns: ["kara-reason", "node"],
    minReadable: 3,
    grammarPrereqs: ["kara-reason", "node"],
  },
  {
    id: "obligation",
    label: "Must / have to",
    patterns: ["nakereba-naranai", "nakereba-ikenai", "nakya", "nai-to-ikenai"],
    minReadable: 3,
    grammarPrereqs: ["nakereba-naranai", "nakereba-ikenai", "nakya", "nai-to-ikenai"],
  },
  {
    id: "sequential",
    label: "After / while doing",
    patterns: ["te-kara", "te-iru", "te-shimau", "te-oku", "te-miru"],
    minReadable: 3,
    grammarPrereqs: ["te-kara", "te-iru", "te-shimau", "te-oku", "te-miru"],
  },
  {
    id: "desire",
    label: "Want to / easy / hard",
    patterns: ["tai", "yasui", "nikui"],
    minReadable: 3,
    grammarPrereqs: ["tai", "yasui", "nikui"],
  },
  {
    id: "giving",
    label: "Giving and receiving",
    patterns: ["te-ageru", "te-kureru", "te-morau"],
    minReadable: 3,
    grammarPrereqs: ["te-ageru", "te-kureru", "te-morau"],
  },
  {
    id: "reported",
    label: "I think / seems like",
    patterns: ["to-omou", "rashii", "kamoshirenai", "deshou"],
    minReadable: 3,
    grammarPrereqs: ["to-omou", "rashii", "kamoshirenai", "deshou"],
  },
  {
    id: "contrast",
    label: "Even though / only",
    patterns: ["noni", "nai-de", "nai-request"],
    minReadable: 3,
    grammarPrereqs: ["noni", "nai-de", "nai-request"],
  },
  {
    id: "request",
    label: "Requests and proposals",
    patterns: ["te-request", "mashou", "kata"],
    minReadable: 3,
    grammarPrereqs: ["te-request", "mashou", "kata"],
  },
];

/**
 * All grammar pattern IDs claimed by later tiers, given a tier index.
 * Used to ensure each sentence belongs to exactly one tier — the earliest
 * (simplest) one whose patterns match it.
 */
function laterTierPatterns(tierIndex: number): Set<string> {
  return new Set(
    SENTENCE_ORDERING_TIERS.slice(tierIndex + 1).flatMap((t) => [...t.patterns]),
  );
}

/**
 * Readable assembly items that belong to this tier.
 *
 * A sentence belongs to a tier when:
 *   1. It is readable (all content lemmas known).
 *   2. It has ≤4 pieces — short enough for a clear drag exercise.
 *   3. At least one of its pattern tags is in this tier's pattern set.
 *   4. None of its pattern tags belong to a later (more complex) tier.
 *
 * Rule 4 ensures each sentence lands in exactly one tier: a sentence tagged
 * both `wo` (simple) and `tara` (conditional) appears only in the conditional
 * tier, because `tara` is a later, more complex pattern.
 */
export function readableAssemblyForTier(
  tier: AssemblyTier,
  history: HistoryFile,
): readonly AssemblyItem[] {
  const tierIndex = SENTENCE_ORDERING_TIERS.indexOf(tier);
  const later = laterTierPatterns(tierIndex);
  const mine = new Set(tier.patterns);
  return readableAssembly(history).filter(
    (it) =>
      it.pieces.length <= 4 &&
      it.p.some((p) => mine.has(p)) &&
      !it.p.some((p) => later.has(p)),
  );
}

/**
 * Every distinct grammar fact represented by the readable sentences in this
 * tier. Passed to the session so the drill can credit assembly answers against
 * the correct fact IDs.
 */
export function tierAssemblyFacts(
  tier: AssemblyTier,
  history: HistoryFile,
): FactId[] {
  const out = new Set<FactId>();
  for (const item of readableAssemblyForTier(tier, history)) {
    for (const fact of assemblyFacts(item)) out.add(fact);
  }
  return [...out];
}

/**
 * Roll one readable assembly item, or null when the learner can read none yet
 * — the ordinary early answer, exactly like the selection corpus. `rng` is
 * injectable for tests.
 */
export function pickAssembly(
  history: HistoryFile,
  rng: Rng = Math.random,
): AssemblyItem | null {
  const pool = readableAssembly(history);
  if (pool.length === 0) return null;
  return pool[Math.floor(rng() * pool.length)] ?? pool[0];
}
