// The ASSEMBLY corpus: sentences broken into ordered drag pieces, for the
// "build the sentence" question type (task 11).
//
// Generated by scripts/ingest/assembly.py from grammar-corpus.json, re-tokenized
// with fugashi + unidic-lite (the SAME morphological tagger the grammar corpus
// was built with). See that script for the two filters that keep this honest,
// which are the whole reason this can exist beside the never-mark-wrong rule:
//
//   1. Word boundaries come from the tagger, never a hand-rolled guess. A
//      particle rides with its preceding content word (ごはん+を = one piece
//      "ごはんを"), exactly as the approved mockup draws it, so the test is WORD
//      ORDER, never particle choice.
//   2. Only sentences whose piece order is GENUINELY FIXED survive. A sentence
//      that admits more than one natural order (two case-marked arguments that
//      scramble, coordinate clauses that reorder) is DROPPED, not graded — see
//      `single_order` in the ingest script. 596 of 8,547 survive; the small
//      honest set is the point.
//
// The known-words gate (`pickAssembly`) is applied at RUNTIME, per learner,
// exactly like the selection corpus's readability gate: an item is offered only
// when every content lemma in it is a word the learner knows.

import assemblyJson from "./generated/assembly-corpus.json" with { type: "json" };
import { patternMeaningFactId } from "./grammar/index.ts";
import { lemmaKnown } from "../lib/grammar/readable.ts";
import { factInfo } from "../lib/facts.ts";
import type { Rng } from "../lib/grammar/vehicles.ts";
import type { FactId, HistoryFile } from "../types/index.ts";

/** One draggable piece: its surface text, and the dictionary form of its head
 * content word (for a meaning hint), or null when the piece has no content head
 * (a bare adverb/particle cluster). */
export interface AssemblyPiece {
  readonly t: string;
  readonly h: string | null;
}

/** One assembly item — a sentence to rebuild from its pieces. */
export interface AssemblyItem {
  /** Tatoeba sentence id, for attribution and reporting a bad item. */
  readonly id: number;
  /** The human English translation — the prompt. */
  readonly en: string;
  /** The canonical sentence, pieces joined. */
  readonly jp: string;
  /** The pieces IN CANONICAL ORDER. The one accepted order is this sequence. */
  readonly pieces: readonly AssemblyPiece[];
  /** Content lemmas, for the known-words gate. */
  readonly v: readonly string[];
  /** The grammar patterns this sentence matched — the facts a correct assembly
   * credits. See `assemblyFacts`. */
  readonly p: readonly string[];
}

/** Short, reviewed exercises that keep every tier reachable from the teaching
 * curriculum. The generated grammar corpus is reference-rich, not beginner-
 * ordered: it has almost no plain SOV sentences, and several later tiers only
 * use vocabulary that the Vocabulary track never teaches at all.
 *
 * The first three rows for each tier are natural, imitable sentences a learner
 * can safely copy (Sam sign-off 2026-08-19, SAK-45). They no longer have to
 * stay within an already-known/first-N vocabulary set — concrete, genuinely
 * beginner-simple words are fine even if the learner hasn't met them yet; the
 * per-learner known-words gate (`assemblyReadable`) still decides at runtime
 * whether any one learner can read a given item. Grammaticalized helpers such
 * as ください, くれる and ならない are supplied by the tier's grammar lesson,
 * so they are intentionally not `v` vocabulary prerequisites. The generated
 * corpus still supplies variety as the learner's vocabulary grows. */
const CURATED_ASSEMBLY: readonly AssemblyItem[] = [
  // Simple sentences. Content approved by Sam 2026-08-19 (SAK-45), replacing
  // the earlier template-generated set — see the ticket for the full table.
  {
    id: -1,
    en: "I drink water.",
    jp: "私は水を飲む。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "水を", h: "水" },
      { t: "飲む。", h: "飲む" },
    ],
    v: ["私", "水", "飲む"],
    // Tagged with the actual particle this sentence turns on (を, "marks the
    // direct object" — a real registered grammar recipe), not the tier id
    // "simple". Tagging the tier's own id here used to leave assemblyFacts()
    // with nothing to credit: "simple" was never a grammar recipe, so
    // patternMeaningFactId("simple") resolved to no fact and every showing of
    // this item credited zero facts (SAK-18). Every other curated item in this
    // file is already tagged with the real pattern it exercises — this tier's
    // items were the one place that convention slipped.
    p: ["wo"],
  },
  {
    id: -2,
    en: "What do I drink?",
    jp: "私は何を飲む？",
    pieces: [
      { t: "私は", h: "私" },
      { t: "何を", h: "何" },
      { t: "飲む？", h: "飲む" },
    ],
    v: ["私", "何", "飲む"],
    p: ["wo"],
  },
  {
    id: -3,
    en: "I read a book.",
    jp: "私は本を読む。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "本を", h: "本" },
      { t: "読む。", h: "読む" },
    ],
    v: ["私", "本", "読む"],
    p: ["wo"],
  },

  // Te-form links and helpers.
  {
    id: -11,
    en: "I accidentally forgot my homework.",
    jp: "私は宿題を忘れてしまった。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "宿題を", h: "宿題" },
      { t: "忘れてしまった。", h: "忘れる" },
    ],
    v: ["私", "宿題", "忘れる"],
    p: ["te-shimau"],
  },
  {
    id: -12,
    en: "I'll try eating a new dish.",
    jp: "私は新しい料理を食べてみる。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "新しい料理を", h: "料理" },
      { t: "食べてみる。", h: "食べる" },
    ],
    v: ["私", "新しい", "料理", "食べる"],
    p: ["te-miru"],
  },
  {
    id: -13,
    en: "I have an umbrella.",
    jp: "私は傘を持っている。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "傘を", h: "傘" },
      { t: "持っている。", h: "持つ" },
    ],
    v: ["私", "傘", "持つ"],
    p: ["te-iru"],
  },

  // Requests and proposals.
  {
    id: -21,
    en: "Please read this book.",
    jp: "この本を読んでください。",
    pieces: [
      { t: "この本を", h: "本" },
      { t: "読んで", h: "読む" },
      { t: "ください。", h: null },
    ],
    v: ["本", "読む"],
    p: ["te-request"],
  },
  {
    id: -22,
    en: "Please don't forget your phone.",
    jp: "電話を忘れないでください。",
    pieces: [
      { t: "電話を", h: "電話" },
      { t: "忘れないで", h: "忘れる" },
      { t: "ください。", h: null },
    ],
    v: ["電話", "忘れる"],
    p: ["nai-request"],
  },
  {
    id: -23,
    en: "Let's listen to music.",
    jp: "音楽を聞きましょう。",
    pieces: [
      { t: "音楽を", h: "音楽" },
      { t: "聞き", h: "聞く" },
      { t: "ましょう。", h: null },
    ],
    v: ["音楽", "聞く"],
    p: ["mashou"],
  },

  // Desire, ease and difficulty.
  {
    id: -31,
    en: "I want to see my friend.",
    jp: "私は友達に会いたい。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "友達に", h: "友達" },
      { t: "会い", h: "会う" },
      { t: "たい。", h: null },
    ],
    v: ["私", "友達", "会う"],
    p: ["tai"],
  },
  {
    id: -32,
    en: "This tea is easy to drink.",
    jp: "このお茶は飲みやすい。",
    pieces: [
      { t: "このお茶は", h: "お茶" },
      { t: "飲み", h: "飲む" },
      { t: "やすい。", h: null },
    ],
    v: ["お茶", "飲む"],
    p: ["yasui"],
  },
  {
    id: -33,
    en: "This name is hard to say.",
    jp: "この名前は言いにくい。",
    pieces: [
      { t: "この名前は", h: "名前" },
      { t: "言い", h: "言う" },
      { t: "にくい。", h: null },
    ],
    v: ["名前", "言う"],
    p: ["nikui"],
  },

  // Conditions.
  {
    id: -41,
    en: "If it rains, I'll stay home.",
    jp: "雨が降ったら、私は家にいる。",
    pieces: [
      { t: "雨が降ったら、", h: "降る" },
      { t: "私は", h: "私" },
      { t: "家に", h: "家" },
      { t: "いる。", h: "いる" },
    ],
    v: ["雨", "降る", "私", "家", "いる"],
    p: ["tara"],
  },
  {
    id: -42,
    en: "If you turn on the light, the room gets bright.",
    jp: "電気をつければ、部屋が明るくなる。",
    pieces: [
      { t: "電気をつければ、", h: "つける" },
      { t: "部屋が", h: "部屋" },
      { t: "明るく", h: "明るい" },
      { t: "なる。", h: "なる" },
    ],
    v: ["電気", "つける", "部屋", "明るい", "なる"],
    p: ["ba"],
  },
  {
    id: -43,
    en: "If I have money, I'll go on a trip.",
    jp: "お金があるなら、私は旅行に行く。",
    pieces: [
      { t: "お金があるなら、", h: "ある" },
      { t: "私は", h: "私" },
      { t: "旅行に", h: "旅行" },
      { t: "行く。", h: "行く" },
    ],
    v: ["お金", "ある", "私", "旅行", "行く"],
    p: ["nara"],
  },

  // Reasons and results.
  {
    id: -51,
    en: "Because I'm sleepy, I go to bed early.",
    jp: "眠いから、私は早く寝る。",
    pieces: [
      { t: "眠いから、", h: "眠い" },
      { t: "私は", h: "私" },
      { t: "早く寝る。", h: "寝る" },
    ],
    v: ["眠い", "私", "早い", "寝る"],
    p: ["kara-reason"],
  },
  {
    id: -52,
    en: "Because I don't have time, I hurry.",
    jp: "時間がないので、私は急ぐ。",
    pieces: [
      { t: "時間がないので、", h: "時間" },
      { t: "私は", h: "私" },
      { t: "急ぐ。", h: "急ぐ" },
    ],
    v: ["時間", "ない", "私", "急ぐ"],
    p: ["node"],
  },
  {
    id: -53,
    en: "Because it's dangerous, I won't go.",
    jp: "危ないから、私は行かない。",
    pieces: [
      { t: "危ないから、", h: "危ない" },
      { t: "私は", h: "私" },
      { t: "行かない。", h: "行く" },
    ],
    v: ["危ない", "私", "行く"],
    p: ["kara-reason"],
  },

  // Giving and receiving help.
  {
    id: -61,
    en: "My friend lent me a book.",
    jp: "友達が私に本を貸してくれた。",
    pieces: [
      { t: "友達が", h: "友達" },
      { t: "私に", h: "私" },
      { t: "本を", h: "本" },
      { t: "貸してくれた。", h: "貸す" },
    ],
    v: ["友達", "私", "本", "貸す"],
    p: ["te-kureru"],
  },
  {
    id: -62,
    en: "I had my friend take a photo for me.",
    jp: "私は友達に写真を撮ってもらった。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "友達に", h: "友達" },
      { t: "写真を", h: "写真" },
      { t: "撮ってもらった。", h: "撮る" },
    ],
    v: ["私", "友達", "写真", "撮る"],
    p: ["te-morau"],
  },
  {
    id: -63,
    en: "I lent my friend an umbrella.",
    jp: "私は友達に傘を貸してあげた。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "友達に", h: "友達" },
      { t: "傘を", h: "傘" },
      { t: "貸してあげた。", h: "貸す" },
    ],
    v: ["私", "友達", "傘", "貸す"],
    p: ["te-ageru"],
  },

  // Contrast and doing something without another action.
  {
    id: -71,
    en: "I left without taking an umbrella.",
    jp: "私は傘を持たないで出た。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "傘を持たないで", h: "持つ" },
      { t: "出た。", h: "出る" },
    ],
    v: ["私", "傘", "持つ", "出る"],
    p: ["nai-de"],
  },
  {
    id: -72,
    en: "Even though the weather is nice, I stay home.",
    jp: "天気がいいのに、私は家にいる。",
    pieces: [
      { t: "天気がいいのに、", h: "いい" },
      { t: "私は", h: "私" },
      { t: "家にいる。", h: "いる" },
    ],
    v: ["天気", "いい", "私", "家", "いる"],
    p: ["noni"],
  },
  {
    id: -73,
    en: "I went to sleep without doing my homework.",
    jp: "私は宿題をしないで寝た。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "宿題をしないで", h: "する" },
      { t: "寝た。", h: "寝る" },
    ],
    v: ["私", "宿題", "する", "寝る"],
    p: ["nai-de"],
  },

  // Obligation.
  {
    id: -81,
    en: "I have to do my homework.",
    jp: "私は宿題をしなければならない。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "宿題を", h: "宿題" },
      { t: "しなければ", h: "する" },
      { t: "ならない。", h: null },
    ],
    v: ["私", "宿題", "する"],
    p: ["nakereba-naranai"],
  },
  {
    id: -82,
    en: "I have to get up early.",
    jp: "私は早く起きなければならない。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "早く", h: "早い" },
      { t: "起きなければ", h: "起きる" },
      { t: "ならない。", h: null },
    ],
    v: ["私", "早い", "起きる"],
    p: ["nakereba-naranai"],
  },
  {
    id: -83,
    en: "I have to take medicine.",
    jp: "私は薬を飲まないといけない。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "薬を", h: "薬" },
      { t: "飲まないと", h: "飲む" },
      { t: "いけない。", h: null },
    ],
    v: ["私", "薬", "飲む"],
    p: ["nai-to-ikenai"],
  },

  // Reports, inference and stance.
  {
    id: -91,
    en: "I think this movie is interesting.",
    jp: "私はこの映画が面白いと思う。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "この映画が面白いと", h: "面白い" },
      { t: "思う。", h: "思う" },
    ],
    v: ["私", "映画", "面白い", "思う"],
    p: ["to-omou"],
  },
  {
    id: -92,
    en: "It might rain tomorrow.",
    jp: "明日は雨かもしれない。",
    pieces: [
      { t: "明日は", h: "明日" },
      { t: "雨", h: "雨" },
      { t: "かもしれない。", h: null },
    ],
    v: ["明日", "雨"],
    p: ["kamoshirenai"],
  },
  {
    id: -93,
    en: "He seems to be busy.",
    jp: "彼は忙しいらしい。",
    pieces: [
      { t: "彼は", h: "彼" },
      { t: "忙しい", h: "忙しい" },
      { t: "らしい。", h: null },
    ],
    v: ["彼", "忙しい"],
    p: ["rashii"],
  },

  // Additional reviewed variety, unlocked as its words are learned.
  {
    id: -101,
    en: "Saku ate sushi.",
    jp: "サクは寿司を食べた。",
    pieces: [
      { t: "サクは", h: null },
      { t: "寿司を", h: "寿司" },
      { t: "食べた。", h: "食べる" },
    ],
    v: ["寿司", "食べる"],
    p: ["wo"],
  },
  {
    id: -102,
    en: "Saku went to the store.",
    jp: "サクは店に行った。",
    pieces: [
      { t: "サクは", h: null },
      { t: "店に", h: "店" },
      { t: "行った。", h: "行く" },
    ],
    v: ["店", "行く"],
    p: ["ni"],
  },
  {
    id: -103,
    en: "Saku played with the red ball.",
    jp: "サクは赤いボールで遊んだ。",
    pieces: [
      { t: "サクは", h: null },
      { t: "赤いボールで", h: "ボール" },
      { t: "遊んだ。", h: "遊ぶ" },
    ],
    v: ["赤い", "ボール", "遊ぶ"],
    p: ["de"],
  },
  {
    id: -201,
    en: "Please read this sentence.",
    jp: "この文を読んでください。",
    pieces: [
      { t: "この文を", h: "文" },
      { t: "読んで", h: "読む" },
      { t: "ください。", h: "くださる" },
    ],
    v: ["文", "読む", "くださる"],
    p: ["te-request"],
  },
  {
    id: -202,
    en: "Let's start now.",
    jp: "今、始めましょう。",
    pieces: [
      { t: "今、", h: "今" },
      { t: "始め", h: "始める" },
      { t: "ましょう。", h: null },
    ],
    v: ["今", "始める"],
    p: ["mashou"],
  },
  {
    id: -203,
    en: "Please write your name here.",
    jp: "ここに名前を書いてください。",
    pieces: [
      { t: "ここに", h: "ここ" },
      { t: "名前を", h: "名前" },
      { t: "書いて", h: "書く" },
      { t: "ください。", h: "くださる" },
    ],
    v: ["ここ", "名前", "書く", "くださる"],
    p: ["te-request"],
  },
  {
    id: -301,
    en: "I want to go to Japan.",
    jp: "私は日本へ行きたい。",
    pieces: [
      { t: "私は", h: "私" },
      { t: "日本へ", h: "日本" },
      { t: "行き", h: "行く" },
      { t: "たい。", h: null },
    ],
    v: ["私", "日本", "行く"],
    p: ["tai"],
  },
  {
    id: -302,
    en: "This book is easy to read.",
    jp: "この本は読みやすい。",
    pieces: [
      { t: "この本は", h: "本" },
      { t: "読み", h: "読む" },
      { t: "やすい。", h: null },
    ],
    v: ["本", "読む"],
    p: ["yasui"],
  },
  {
    id: -303,
    en: "This kanji is hard to remember.",
    jp: "この漢字は覚えにくい。",
    pieces: [
      { t: "この漢字は", h: "漢字" },
      { t: "覚え", h: "覚える" },
      { t: "にくい。", h: null },
    ],
    v: ["漢字", "覚える"],
    p: ["nikui"],
  },
  {
    id: -401,
    en: "Saku helped me.",
    jp: "サクが手伝ってくれた。",
    pieces: [
      { t: "サクが", h: null },
      { t: "手伝って", h: "手伝う" },
      { t: "くれた。", h: "くれる" },
    ],
    v: ["手伝う", "くれる"],
    p: ["te-kureru"],
  },
  {
    id: -402,
    en: "My mother cooked for me.",
    jp: "母が料理してくれた。",
    pieces: [
      { t: "母が", h: "母" },
      { t: "料理して", h: "料理" },
      { t: "くれた。", h: "くれる" },
    ],
    v: ["母", "料理", "くれる"],
    p: ["te-kureru"],
  },
  {
    id: -403,
    en: "I had my teacher explain it.",
    jp: "先生に説明してもらった。",
    pieces: [
      { t: "先生に", h: "先生" },
      { t: "説明して", h: "説明" },
      { t: "もらった。", h: "もらう" },
    ],
    v: ["先生", "説明", "もらう"],
    p: ["te-morau"],
  },
];

export const ASSEMBLY: readonly AssemblyItem[] = [
  ...CURATED_ASSEMBLY,
  ...(assemblyJson as readonly AssemblyItem[]),
];
export const ASSEMBLY_QUIZ_TARGET = 12;

/**
 * The canonical order for an item — the one accepted answer.
 */
export function canonicalOrder(item: AssemblyItem): readonly string[] {
  return item.pieces.map((p) => p.t);
}

/**
 * Does this order of piece surfaces grade CORRECT?
 *
 * There is exactly one accepted order: the canonical one. Word order is the
 * whole question, so this is a straight sequence comparison — no particle
 * leniency to get wrong, because particles ride inside the pieces.
 */
export function gradeAssembly(item: AssemblyItem, order: readonly string[]): boolean {
  const canon = canonicalOrder(item);
  if (order.length !== canon.length) return false;
  return order.every((t, i) => t === canon[i]);
}

/**
 * The facts a correct assembly credits — the MEANING fact of each pattern the
 * sentence uses, filtered to those the registry actually has. Placing a pattern
 * correctly in a whole sentence is evidence about where it goes, which is the
 * standing the selection cloze already moves; assembly is a second way to
 * exercise the same facts rather than a new kind of score.
 */
export function assemblyFacts(item: AssemblyItem): FactId[] {
  return item.p.map(patternMeaningFactId).filter((f) => factInfo(f));
}

/**
 * Every distinct fact represented by assembly items the learner can currently
 * read. Used to gate and label sentence-ordering drills started from Learn.
 */
export function readableAssemblyFacts(history: HistoryFile): FactId[] {
  const out = new Set<FactId>();
  for (const item of readableAssembly(history)) {
    for (const fact of assemblyFacts(item)) out.add(fact);
  }
  return [...out];
}

/**
 * Can the learner read this item — every content lemma known?
 */
export function assemblyReadable(item: AssemblyItem, history: HistoryFile): boolean {
  return item.v.every((lemma) => lemmaKnown(lemma, history));
}

/**
 * Every assembly item the learner can read right now.
 */
export function readableAssembly(history: HistoryFile): readonly AssemblyItem[] {
  return ASSEMBLY.filter((it) => assemblyReadable(it, history));
}

/**
 * One structural tier in the sentence-ordering track — a named sentence type
 * (e.g. "Conditional sentences") defined by the grammar pattern IDs that tag
 * its sentences in the assembly corpus.
 *
 * Tiers are ordered by pedagogical complexity: Simple first, then Conditional,
 * Causal, Obligation and so on. The learner sees them as sentence STRUCTURE
 * lessons, not grammar lessons — the pattern IDs are the engine's internal
 * classification, never shown.
 */
export interface AssemblyTier {
  readonly id: string;
  /** Learner-visible name, shown on the lesson card. */
  readonly label: string;
  /** Assembly corpus pattern IDs (`item.p`) that define this tier. A sentence
   * belongs to the FIRST tier whose pattern set intersects its own pattern
   * list, provided no later-tier pattern also appears (see
   * `readableAssemblyForTier`). */
  readonly patterns: readonly string[];
  /** Minimum number of readable sentences required for the tier to unlock.
   * Below this, the learner cannot do a meaningful drill, so the tier is
   * skipped rather than shown as locked. */
  readonly minReadable: number;
  /**
   * Grammar pattern IDs that must have been taught in the grammar track before
   * this tier unlocks. At least ONE must be learned (seen, claimed or tested).
   *
   * For every tier the prereqs are the patterns that describe the sentence
   * structure this tier practices, so the learner knows what the pattern means
   * before they practise placing it — including the simple tier, whose は/が
   * are real grammar-track lessons now, not assumed-known structural markers.
   */
  readonly grammarPrereqs: readonly string[];
}

/**
 * The ordered sentence-structure tiers the sentence-ordering track teaches.
 *
 * Each tier needs enough vocabulary to read its sentences; the planner also
 * applies the `grammarPrereqs` ANY-of gate below. The tiers are ordered from
 * structurally simplest to most complex, so the learner always encounters
 * simple particle-marked SOV sentences first. Every tier after that
 * follows the first point at which one of its prerequisite patterns appears in
 * CURRICULUM_PATTERNS (src/lib/grammar-lesson.ts): sequence, requests,
 * contrast/negative linking, desire, conditionals, cause, giving/receiving,
 * obligation, then reported stance.
 */
export const SENTENCE_ORDERING_TIERS: readonly AssemblyTier[] = [
  {
    id: "simple",
    label: "Simple sentences",
    // Every entry here is a REGISTERED grammar recipe (src/data/grammar/recipes.ts)
    // — the case particles a plain SOV sentence turns on. There is no "simple"
    // pattern id: this tier's own id used to double as a pattern tag on its
    // curated items, but patternMeaningFactId("simple") resolves to no fact, so
    // assemblyFacts() silently credited nothing for every one of them (SAK-18).
    // "ni"/"de" cover the two curated items (-102, -103) that turn on location/
    // instrument marking rather than a direct object.
    patterns: ["wo", "ni", "de", "e", "made", "made-ni", "dake", "kara-source"],
    minReadable: 3,
    grammarPrereqs: ["wa", "ga"],
  },
  {
    id: "sequential",
    label: "Te-form links and helpers",
    patterns: ["te-kara", "te-iru", "te-shimau", "te-oku", "te-miru"],
    minReadable: 3,
    grammarPrereqs: ["te-kara", "te-iru", "te-shimau", "te-oku", "te-miru"],
  },
  {
    id: "request",
    label: "Requests and proposals",
    patterns: ["te-request", "nai-request", "mashou"],
    minReadable: 3,
    grammarPrereqs: ["te-request", "nai-request", "mashou"],
  },
  {
    id: "desire",
    label: "Want to / easy / hard",
    patterns: ["tai", "yasui", "nikui"],
    minReadable: 3,
    grammarPrereqs: ["tai", "yasui", "nikui"],
  },
  {
    id: "conditional",
    label: "Conditional sentences",
    patterns: ["tara", "ba", "nara"],
    minReadable: 3,
    grammarPrereqs: ["tara", "ba", "nara"],
  },
  {
    id: "causal",
    label: "Because / so",
    patterns: ["kara-reason", "node"],
    minReadable: 3,
    grammarPrereqs: ["kara-reason", "node"],
  },
  {
    id: "giving",
    label: "Giving and receiving",
    patterns: ["te-ageru", "te-kureru", "te-morau"],
    minReadable: 3,
    grammarPrereqs: ["te-ageru", "te-kureru", "te-morau"],
  },
  {
    id: "contrast",
    label: "Even though / without",
    patterns: ["noni", "nai-de"],
    minReadable: 3,
    grammarPrereqs: ["noni", "nai-de"],
  },
  {
    id: "obligation",
    label: "Must / have to",
    patterns: ["nakereba-naranai", "nakereba-ikenai", "nakya", "nai-to-ikenai"],
    minReadable: 3,
    grammarPrereqs: ["nakereba-naranai", "nakereba-ikenai", "nakya", "nai-to-ikenai"],
  },
  {
    id: "reported",
    label: "I think / seems like",
    patterns: ["to-omou", "rashii", "kamoshirenai", "deshou"],
    minReadable: 3,
    grammarPrereqs: ["to-omou", "rashii", "kamoshirenai", "deshou"],
  },
];

/** The one unambiguous sentence-ordering tier represented by an assembly item.
 * A sentence that combines two taught structures is useful Japanese, but it is
 * a poor single-lesson exercise: “I'll lend you one if you like” should not be
 * arbitrarily called either Conditional or Giving/receiving. Those compound
 * items stay outside this teaching pool until they have their own lesson. */
export function sentenceOrderingTierForItem(item: AssemblyItem): string | null {
  const matches = SENTENCE_ORDERING_TIERS.filter((tier) =>
    item.p.some((pattern) => tier.patterns.includes(pattern)),
  );
  return matches.length === 1 ? matches[0].id : null;
}

/**
 * Readable assembly items that belong to this tier.
 *
 * A sentence belongs to a tier when:
 *   1. It is readable (all content lemmas known).
 *   2. It has ≤4 pieces — short enough for a clear drag exercise.
 *   3. It maps unambiguously to this one tier.
 */
export function readableAssemblyForTier(
  tier: AssemblyTier,
  history: HistoryFile,
): readonly AssemblyItem[] {
  return readableAssembly(history).filter(
    (it) =>
      it.pieces.length <= 4 &&
      sentenceOrderingTierForItem(it) === tier.id &&
      // なら can also frame a topic (“as for the box”) even when an English
      // translation contains no condition at all. That is valid Japanese, but
      // it does not clearly teach conditional ordering from an English prompt.
      (tier.id !== "conditional" ||
        /\b(if|when|unless|provided|in case)\b/i.test(it.en)),
  );
}

/** Readable exercises from exactly the sentence-ordering tiers requested. */
export function readableAssemblyForTiers(
  tierIds: readonly string[],
  history: HistoryFile,
): readonly AssemblyItem[] {
  const wanted = new Set(tierIds);
  const seen = new Set<number>();
  const out: AssemblyItem[] = [];
  for (const tier of SENTENCE_ORDERING_TIERS) {
    if (!wanted.has(tier.id)) continue;
    for (const item of readableAssemblyForTier(tier, history)) {
      if (seen.has(item.id)) continue;
      seen.add(item.id);
      out.push(item);
    }
  }
  return out;
}

/** Roll one readable exercise from the requested learned/taught tiers. */
export function pickAssemblyForTiers(
  history: HistoryFile,
  tierIds: readonly string[],
  rng: Rng = Math.random,
): AssemblyItem | null {
  const pool = readableAssemblyForTiers(tierIds, history);
  if (pool.length === 0) return null;
  return pool[Math.floor(rng() * pool.length)] ?? pool[0];
}

/**
 * Every distinct grammar fact represented by the readable sentences in this
 * tier. Passed to the session so the drill can credit assembly answers against
 * the correct fact IDs.
 */
export function tierAssemblyFacts(
  tier: AssemblyTier,
  history: HistoryFile,
): FactId[] {
  const out = new Set<FactId>();
  for (const item of readableAssemblyForTier(tier, history)) {
    for (const fact of assemblyFacts(item)) out.add(fact);
  }
  return [...out];
}

/**
 * Roll one readable assembly item, or null when the learner can read none yet
 * — the ordinary early answer, exactly like the selection corpus. `rng` is
 * injectable for tests.
 */
export function pickAssembly(
  history: HistoryFile,
  rng: Rng = Math.random,
): AssemblyItem | null {
  const pool = readableAssembly(history);
  if (pool.length === 0) return null;
  return pool[Math.floor(rng() * pool.length)] ?? pool[0];
}
