// The ASSEMBLY corpus: sentences broken into ordered drag pieces, for the
// "build the sentence" question type (task 11).
//
// Generated by scripts/ingest/assembly.py from grammar-corpus.json, re-tokenized
// with fugashi + unidic-lite (the SAME morphological tagger the grammar corpus
// was built with). See that script for the two filters that keep this honest,
// which are the whole reason this can exist beside the never-mark-wrong rule:
//
//   1. Word boundaries come from the tagger, never a hand-rolled guess. A
//      particle rides with its preceding content word (ごはん+を = one piece
//      "ごはんを"), exactly as the approved mockup draws it, so the test is WORD
//      ORDER, never particle choice.
//   2. Only sentences whose piece order is GENUINELY FIXED survive. A sentence
//      that admits more than one natural order (two case-marked arguments that
//      scramble, coordinate clauses that reorder) is DROPPED, not graded — see
//      `single_order` in the ingest script. 596 of 8,547 survive; the small
//      honest set is the point.
//
// The known-words gate (`pickAssembly`) is applied at RUNTIME, per learner,
// exactly like the selection corpus's readability gate: an item is offered only
// when every content lemma in it is a word the learner knows.

import assemblyJson from "./generated/assembly-corpus.json" with { type: "json" };
import { VOCAB } from "./vocab.ts";
import { patternMeaningFactId } from "./grammar/index.ts";
import { lemmaKnown } from "../lib/grammar/readable.ts";
import { factInfo } from "../lib/facts.ts";
import type { Rng } from "../lib/grammar/vehicles.ts";
import type { FactId, HistoryFile } from "../types/index.ts";

/** One draggable piece: its surface text, and the dictionary form of its head
 * content word (for a meaning hint), or null when the piece has no content head
 * (a bare adverb/particle cluster). */
export interface AssemblyPiece {
  readonly t: string;
  readonly h: string | null;
}

/** One assembly item — a sentence to rebuild from its pieces. */
export interface AssemblyItem {
  /** Tatoeba sentence id, for attribution and reporting a bad item. */
  readonly id: number;
  /** The human English translation — the prompt. */
  readonly en: string;
  /** The canonical sentence, pieces joined. */
  readonly jp: string;
  /** The pieces IN CANONICAL ORDER. The one accepted order is this sequence. */
  readonly pieces: readonly AssemblyPiece[];
  /** Content lemmas, for the known-words gate. */
  readonly v: readonly string[];
  /** The grammar patterns this sentence matched — the facts a correct assembly
   * credits. See `assemblyFacts`. */
  readonly p: readonly string[];
}

export const ASSEMBLY: readonly AssemblyItem[] = assemblyJson as readonly AssemblyItem[];

/** keb OR reb → glosses, built once, for the per-piece meaning hint. */
const GLOSS_BY_SPELLING: ReadonlyMap<string, readonly string[]> = (() => {
  const map = new Map<string, readonly string[]>();
  for (const w of VOCAB) {
    for (const spelling of new Set([w.keb, w.reb])) {
      if (!map.has(spelling)) map.set(spelling, w.glosses);
    }
  }
  return map;
})();

/**
 * The meaning hint for a piece — the first gloss of its head content word, or
 * null when the piece has no content head or the word is not in the vocabulary.
 *
 * DRAFT COPY: this glosses only the head word (ごはんを → "meal"), not the whole
 * piece with its particle. It is honest and one tap away, per the mockup, but
 * the exact wording is not yet reviewed.
 */
export function pieceHint(piece: AssemblyPiece): string | null {
  if (!piece.h) return null;
  return GLOSS_BY_SPELLING.get(piece.h)?.[0] ?? null;
}

/**
 * The canonical order for an item — the one accepted answer.
 */
export function canonicalOrder(item: AssemblyItem): readonly string[] {
  return item.pieces.map((p) => p.t);
}

/**
 * Does this order of piece surfaces grade CORRECT?
 *
 * There is exactly one accepted order: the canonical one. Word order is the
 * whole question, so this is a straight sequence comparison — no particle
 * leniency to get wrong, because particles ride inside the pieces.
 */
export function gradeAssembly(item: AssemblyItem, order: readonly string[]): boolean {
  const canon = canonicalOrder(item);
  if (order.length !== canon.length) return false;
  return order.every((t, i) => t === canon[i]);
}

/**
 * The facts a correct assembly credits — the MEANING fact of each pattern the
 * sentence uses, filtered to those the registry actually has. Placing a pattern
 * correctly in a whole sentence is evidence about where it goes, which is the
 * standing the selection cloze already moves; assembly is a second way to
 * exercise the same facts rather than a new kind of score.
 */
export function assemblyFacts(item: AssemblyItem): FactId[] {
  return item.p.map(patternMeaningFactId).filter((f) => factInfo(f));
}

/**
 * Can the learner read this item — every content lemma known?
 */
export function assemblyReadable(item: AssemblyItem, history: HistoryFile): boolean {
  return item.v.every((lemma) => lemmaKnown(lemma, history));
}

/**
 * Every assembly item the learner can read right now.
 */
export function readableAssembly(history: HistoryFile): readonly AssemblyItem[] {
  return ASSEMBLY.filter((it) => assemblyReadable(it, history));
}

/**
 * Roll one readable assembly item, or null when the learner can read none yet
 * — the ordinary early answer, exactly like the selection corpus. `rng` is
 * injectable for tests.
 */
export function pickAssembly(
  history: HistoryFile,
  rng: Rng = Math.random,
): AssemblyItem | null {
  const pool = readableAssembly(history);
  if (pool.length === 0) return null;
  return pool[Math.floor(rng() * pool.length)] ?? pool[0];
}
