// Kanji that look alike — a DISTRACTOR SOURCE, and nothing else.
//
// WHAT THIS IS ALLOWED TO DO
// ==========================
// It can make 入 a wrong option when the question is 人. That is all.
//
// It may NOT enter the ranking, weight a drill, or appear anywhere that claims
// the user confused two things. A prediction is a guess about a person who has
// not answered yet; a confusion is something they DID. `confused` in
// SessionStats is the second kind and is earned one miss at a time. If a
// predicted pair ever reaches a score, the app starts reporting a weakness the
// user never demonstrated, and the number stops meaning anything.
//
// The value of a prediction is that it works on day one — before there is any
// history to mine, when every distractor would otherwise be random. A random
// wrong option next to 人 teaches nothing, because 山 was never a candidate in
// the reader's head. 入 was.
//
// WHY THERE IS A HAND-AUTHORED TABLE HERE AT ALL
// ==============================================
// Because KRADFILE cannot do this job, which is worth stating plainly since it
// looks like it should. KRADFILE decomposes kanji into components, so it finds
// pairs that share components. But the classic beginner confusions do not share
// components — they ARE components:
//
//   人 / 入   KRADFILE says 人:人 and 入:入. Disjoint. No overlap to find.
//   土 / 士   likewise: each is its own radical.
//   未 / 末   KRADFILE actively SEPARATES these — 未 is ｜二ハ木亠, 末 is
//             ｜一ハ木亠. It records the very difference the eye misses.
//
// So the component graph and the eye disagree, and for this purpose the eye is
// right. What KRADFILE does catch, it catches well (由/甲/申, 犬/太, 永/氷) and
// that is DERIVED_CONFUSABLE below, generated, not hand-kept. The two lists are
// complementary and neither subsumes the other.
//
// TS and not JSON, and not YAML: this one IS hand-authored, so it wants
// comments explaining WHY a pair is here, and it wants the test below to fail
// the build when a typo puts a non-jōyō character in it.

import derivedJson from "./generated/confusable-derived.json" with { type: "json" };

/**
 * Visually confusable jōyō kanji that share no components, so nothing can
 * derive them. Hand-authored; keep it short and keep it honest.
 *
 * The bar is: would a learner reading at speed actually pick the wrong one?
 * Not "do these rhyme" or "are these thematically related" — those make bad
 * distractors, because a distractor that is obviously wrong is a free point,
 * and one that is wrong for a reason the user has to think about is a question.
 */
export const LOOKALIKE_KANJI: readonly (readonly string[])[] = [
  ["人", "入"], // the canonical one. Both 2 strokes, both their own radical.
  ["土", "士"], // differ only in which horizontal is longer.
  ["未", "末"], // same: which horizontal is longer. KRADFILE separates them.
  ["千", "干"], // one stroke's angle.
  ["午", "牛"], // the vertical crosses, or does not.
  ["日", "目"], // one stroke inside. Both extremely early, both very common.
  ["白", "自"], // one stroke on top.
  ["石", "右"], // same parts, different arrangement.
  ["力", "刀"], // both 2 strokes, both early, both radicals.
  ["木", "本"], // one horizontal.
  ["天", "夫", "失"], // which stroke is longest / where it crosses.
  ["見", "貝"], // 見 is 貝 on legs.
  ["休", "体"], // 木 vs 本 again, at compound scale.
  ["東", "車"], // 車 with a 木 through it.
  ["名", "各"], // same components, mirrored arrangement.
  ["待", "持"], // 彳 vs 扌 — the left edge only.
  ["開", "閉", "間", "問", "聞"], // the 門 family: everything is in the middle.
  ["借", "昔"], // 亻 or nothing.
  ["活", "話"], // 氵 vs 訁.
  ["場", "湯"], // 土 vs 氵.
];

/**
 * Groups derived from KRADFILE: identical component multiset AND identical
 * stroke count. 16 groups, 33 kanji — high precision, low recall by design.
 *
 * Generated by scripts/ingest/build.py. Do not hand-edit; add to
 * LOOKALIKE_KANJI instead.
 */
export const DERIVED_CONFUSABLE: readonly (readonly string[])[] =
  derivedJson as readonly (readonly string[])[];

/** kanji → every kanji predicted to be confusable with it, from both sources. */
export const CONFUSABLE_WITH: ReadonlyMap<string, readonly string[]> = build();

function build(): ReadonlyMap<string, readonly string[]> {
  const map = new Map<string, string[]>();
  for (const group of [...LOOKALIKE_KANJI, ...DERIVED_CONFUSABLE]) {
    for (const c of group) {
      const list = map.get(c) ?? [];
      for (const other of group) {
        if (other !== c && !list.includes(other)) list.push(other);
      }
      map.set(c, list);
    }
  }
  return map;
}

/**
 * Plausible wrong options for a question about `c` — the ONLY sanctioned use of
 * any of the above. Returns fewer than `n`, or none at all, rather than padding
 * with random kanji: a distractor nobody would pick is not a distractor.
 */
export function distractorsFor(c: string, n: number): readonly string[] {
  return (CONFUSABLE_WITH.get(c) ?? []).slice(0, n);
}
