// One real sentence per word, for the Library's word page.
//
// The file behind this is generated by scripts/build-word-examples.ts from the
// grammar corpus and the vocabulary. It holds the CHOSEN sentence and nothing
// else — 2,692 rows, 265 KB, against the 1.8 MB corpus it was picked out of —
// because the entry page needs one sentence and should not download 8,689 to
// find it. Why that shape, and how the choice is made, is in
// src/lib/library/word-example.ts.
//
// COVERAGE IS THE POINT OF THE `null` RETURN. 2,692 of 12,553 words (21.4%)
// have a sentence, but 393 of the first 500 words in teaching order (78.6%) do.
// So the section is present on nearly everything a beginner meets and absent
// across the long tail, and the page must render NOTHING when it is absent
// rather than a card explaining itself.
//
// ATTRIBUTION: Tatoeba, CC BY 2.0 FR. `id` is the Tatoeba sentence id and the
// permalink, kept so any sentence on screen traces back to the human who wrote
// it. The acknowledgement itself is the AttributionLink at the foot of the
// page, whose label already names sentence data and Tatoeba by name; see
// src/data/attribution.ts.

import examplesJson from "./generated/word-examples.json" with { type: "json" };

/** A word shown in a real sentence, with a human translation. */
export interface WordExample {
  /** The Tatoeba sentence id — the permalink, and the attribution. */
  readonly id: number;
  readonly jp: string;
  /** A HUMAN translation. Never machine-translated. */
  readonly en: string;
}

/** Tuple-packed on disk: [id, jp, en]. 2,692 rows times three key names is
 * ~40 KB of the same six words, so the keys are put back on here instead. */
const RAW = examplesJson as unknown as Readonly<
  Record<string, readonly [number, string, string]>
>;

/** The example sentence for a word's written form, or null if it has none.
 * Absent is a normal answer for four words in five — see the header. */
export function exampleFor(keb: string): WordExample | null {
  const row = RAW[keb];
  return row ? { id: row[0], jp: row[1], en: row[2] } : null;
}

/** How many words have a sentence. Pinned by a test so a regenerated artifact
 * that silently loses most of its rows is caught. */
export const EXAMPLE_COUNT = Object.keys(RAW).length;
