// One real sentence per word, for the Library's word page.
//
// The file behind this is generated by scripts/build-word-examples.ts from the
// grammar corpus and the vocabulary. It holds the CHOSEN sentence and nothing
// else — 2,692 rows, 265 KB, against the 1.8 MB corpus it was picked out of —
// because the entry page needs one sentence and should not download 8,689 to
// find it. Why that shape, and how the choice is made, is in
// src/lib/library/word-example.ts.
//
// COVERAGE IS THE POINT OF THE `null` RETURN. 2,692 of 12,553 words (21.4%)
// have a sentence, but 393 of the first 500 words in teaching order (78.6%) do.
// So the section is present on nearly everything a beginner meets and absent
// across the long tail, and the page must render NOTHING when it is absent
// rather than a card explaining itself.
//
// ATTRIBUTION: Tatoeba, CC BY 2.0 FR. `id` is the Tatoeba sentence id and the
// permalink, kept so any sentence on screen traces back to the human who wrote
// it. The acknowledgement itself is the "About the data" link in the global
// sidebar (src/components/sidebar.tsx), reachable from every screen; /about/data
// names Tatoeba and the sentence data in full. See src/data/attribution.ts.

import examplesJson from "./generated/word-examples.json" with { type: "json" };

/** A word shown in a real sentence, with a human translation. */
export interface WordExample {
  /** The Tatoeba sentence id — the permalink, and the attribution. */
  readonly id: number;
  readonly jp: string;
  /** A HUMAN translation. Never machine-translated. */
  readonly en: string;
  /**
   * The `[start, end)` span within `jp` where the word's own literal written
   * form (`keb`) appears, to highlight — the same convention SAK-40 uses for
   * a grammar pattern's worked sentence (see SentenceExampleView).
   *
   * Absent, not a guess, when `jp` does not contain `keb` as a literal
   * substring — a conjugated/inflected sentence (くすぐる shown as
   * くすぐらないで) has nothing to point at, and pointing at the wrong
   * characters is worse than pointing at nothing. See build-word-examples.ts
   * for how this is computed.
   */
  readonly span?: readonly [number, number];
}

/** Tuple-packed on disk: [id, jp, en] or [id, jp, en, start, end] when the
 * word's literal written form was found in the sentence. 2,692 rows times
 * three key names is ~40 KB of the same six words, so the keys are put back
 * on here instead. */
const RAW = examplesJson as unknown as Readonly<
  Record<string, readonly [number, string, string] | readonly [number, string, string, number, number]>
>;

/** The example sentence for a word's written form, or null if it has none.
 * Absent is a normal answer for four words in five — see the header. */
export function exampleFor(keb: string): WordExample | null {
  const row = RAW[keb];
  if (!row) return null;
  const [id, jp, en] = row;
  const span = row.length === 5 ? ([row[3], row[4]] as const) : undefined;
  return span ? { id, jp, en, span } : { id, jp, en };
}

/** How many words have a sentence. Pinned by a test so a regenerated artifact
 * that silently loses most of its rows is caught. */
export const EXAMPLE_COUNT = Object.keys(RAW).length;
