// One real sentence per word, for the Library's word page.
//
// The file behind this is generated by scripts/build-word-examples.ts from the
// grammar corpus and the vocabulary. It holds the CHOSEN sentence and nothing
// else — 2,692 rows, 265 KB, against the 1.8 MB corpus it was picked out of —
// because the entry page needs one sentence and should not download 8,689 to
// find it. Why that shape, and how the choice is made, is in
// src/lib/library/word-example.ts.
//
// COVERAGE IS THE POINT OF THE `null` RETURN. 2,692 of 12,553 words (21.4%)
// have a sentence, but 393 of the first 500 words in teaching order (78.6%) do.
// So the section is present on nearly everything a beginner meets and absent
// across the long tail, and the page must render NOTHING when it is absent
// rather than a card explaining itself.
//
// ATTRIBUTION: Tatoeba, CC BY 2.0 FR. `id` is the Tatoeba sentence id and the
// permalink, kept so any sentence on screen traces back to the human who wrote
// it. The acknowledgement itself is the "About the data" link in the global
// sidebar (src/components/sidebar.tsx), reachable from every screen; /about/data
// names Tatoeba and the sentence data in full. See src/data/attribution.ts.
//
// PER-KANJI READINGS (SAK-95). `kr` is a second pass over this same file, run
// by scripts/ingest/sentence_readings.py AFTER build-word-examples.ts: one
// slot per KANJI CHARACTER in `jp`, left to right (kana characters contribute
// no slot). Each slot is either the same [kanji, surface-reading,
// base-reading] triple `VocabRow.align` already uses (src/data/vocab.ts), or
// null when that kanji's in-context reading could not be safely determined —
// a jukujikun the sentence tokenizer's dictionary reading doesn't survive
// aligner's rendaku rules, or a reading vocab.json never happened to attest.
// Null is a normal answer, not a gap to fill in later: see the script's
// module doc for the measured 95% per-kanji coverage and known caveats.

import examplesJson from "./generated/word-examples.json" with { type: "json" };

/** [kanji, surface-reading-in-this-sentence, base-reading], or null when this
 * kanji's reading could not be safely determined. Same shape as one slot of
 * `VocabRow.align`. */
export type KanjiReadingSlot = readonly [string, string, string] | null;

/** A word shown in a real sentence, with a human translation. */
export interface WordExample {
  /** The Tatoeba sentence id — the permalink, and the attribution. */
  readonly id: number;
  readonly jp: string;
  /** A HUMAN translation. Never machine-translated. */
  readonly en: string;
  /**
   * The `[start, end)` span within `jp` where the word's own literal written
   * form (`keb`) appears, to highlight — the same convention SAK-40 uses for
   * a grammar pattern's worked sentence (see SentenceExampleView).
   *
   * Absent, not a guess, when `jp` does not contain `keb` as a literal
   * substring — a conjugated/inflected sentence (くすぐる shown as
   * くすぐらないで) has nothing to point at, and pointing at the wrong
   * characters is worse than pointing at nothing. See build-word-examples.ts
   * for how this is computed.
   */
  readonly span?: readonly [number, number];
  /** Per-kanji reading breakdown of `jp`. See the module header. */
  readonly kr: readonly KanjiReadingSlot[];
}

/** Tuple-packed on disk: [id, jp, en, start, end, kr] — start/end are null
 * when the word's literal written form was not found in the sentence (SAK-94
 * has nothing to highlight then). A fixed six-element shape rather than a
 * variable-length one keeps this single format the only one two independent
 * generation passes (build-word-examples.ts for span, sentence_readings.py
 * for kr) both have to agree on. */
const RAW = examplesJson as unknown as Readonly<
  Record<
    string,
    readonly [number, string, string, number | null, number | null, readonly KanjiReadingSlot[]]
  >
>;

/** The example sentence for a word's written form, or null if it has none.
 * Absent is a normal answer for four words in five — see the header. */
export function exampleFor(keb: string): WordExample | null {
  const row = RAW[keb];
  if (!row) return null;
  const [id, jp, en, start, end, kr] = row;
  const span = start !== null && end !== null ? ([start, end] as const) : undefined;
  return span ? { id, jp, en, span, kr } : { id, jp, en, kr };
}

/** How many words have a sentence. Pinned by a test so a regenerated artifact
 * that silently loses most of its rows is caught. */
export const EXAMPLE_COUNT = Object.keys(RAW).length;
